### ISSUE TITLE
Feature Request: Config Option To Email Admin On Daily.sh Fail

### ISSUE THREAD

**Issue by vectr0n** [librenms/librenms#4778] opened 2016-10-11 21:03 UTC
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.
- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
    Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

LibreNMS Version: 626ce47b0f6f8c99ff15c8ec21ddc7ed37dfbef9
DB Schema: 143
PHP: 5.6.26-0+deb8u1
MySQL: 10.1.18-MariaDB-1~jessie
RRDTool: 1.4.8
SNMP: NET-SNMP 5.7.2.1

Having a config option to email admin if daily.sh fails for whatever reason would be handy as I have noticed a few times it's failed and I had no idea. I think a feature like this could benefit many admins.

**Comment by fenice2** [comment] 2016-10-13 09:24
I'd second this request, it would be extremely useful. I've had the same problem of the daily update failing because of change of owner/group on the files in the librenms directory - probably caused by my inattention when doing a chown. :(

**Comment by laf** [comment] 2016-11-20 02:12
Considering this a duplicate of #4764

**Closed by laf** 2016-11-20 02:12 UTC
