### ISSUE TITLE
Allow IP-based discovery in the presence of DNS

### ISSUE THREAD

**Issue by athompso** [librenms/librenms#4952] opened 2016-11-06 22:59 UTC
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [x] Please provide as much detail as possible.

Component | Version
--------- | -------
LibreNMS  | 1840310f811653653f21622501c6b8d3b50594b7
DB Schema | 148
PHP       | 7.0.12
MySQL     | 5.5.50-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

I need a way to ignore DNS during auto-discovery: I have tons of PTR records but almost zero matching A records, so auto-discovery pretty much utterly fails on this network.
I need to be able to not only proceed witih IP-based adding of the device when there's *no* PTR record (this is already supported), but I need to skip the IP-to-hostname translation step altogether and rely on SNMP sysName or even just the bare IP address instead.

**Comment by Gorian** [comment] 2016-11-07 05:56
FYI, if you paste what's BETWEEN the equal signs, without pasting the actual equal signs, you'll get a nice table instead of that mess of text ;)

**Comment by athompso** [comment] 2016-11-07 11:30
I was able to add a very quick, but only partial, workaround to includes/functions/discovery.php at line 30:
`     if(!empty($config['ignore_dns_ptr'])) {
         $ip = gethostbyname($dst_host);
     }`

**Comment by athompso** [comment] 2016-11-07 11:31
And similarly in snmp-scan.php, at line 116, changing
`addHost(gethostbyaddr($host), '', $config['snmp']['port'], $transport, $config['distributed_poller_group']);`
to
`addHost(($host), '', $config['snmp']['port'], $transport, $config['distributed_poller_group']);`

**Comment by murrant** [comment] 2016-11-11 01:28
So, the issue is you add a device that has valid reverse DNS and it gets added by name then?

Did you try this setting? http://docs.librenms.org/Extensions/Auto-Discovery/#discovering-devices-by-ip

**Comment by athompso** [comment] 2016-11-11 03:28
That's correct.
The setting you mention only appears to apply when the reverse lookup fails.  I do have it enabled.

What I see happening is the discovery process looks up the name (via gethostbyaddr()) which returns a properly-formatted hostname.  At that point, the code assumes the name must be valid and bypasses the discovery_by_ip code because, after all, we have a hostname, right?  It didn't fail, therefore it must be correct... except in my environment, the PTR records got updated (by someone else) without the A records getting updated, so they don't match, and when the autodiscovery uses the resolved hostname, it fails with "host not found".

**Comment by laf** [comment] 2016-11-15 20:34
I'd like to say you should just fix your broken dns, that would be the best / logical fix.

Otherwise what you're asking for us for us to add the ability to skip the rDNS test and just go for adding via IP, is that right?

**Comment by athompso** [comment] 2016-11-17 01:56
Er, yes.  That's precisely my problem.  I'm working on fixing DNS, but it's extremely inconvenient to not even be able to set up monitoring until DNS is fixed.  I suppose I could just point the librenms server to a  DNS server that deliberately lies, but that creates other, even bigger, headaches.

**Comment by laf** [comment] 2016-11-17 06:40
Is what I confirmed you are after above correct though?

**Comment by athompso** [comment] 2016-11-17 10:04
Quoting  myself:
> Er, yes. That's precisely my problem.

**Comment by Gorian** [comment] 2016-11-21 18:25
Could just use the hosts file records matching what you will eventually get in DNS. I do that as a temporary measure and then remove it once DNS propagates.

**Comment by athompso** [comment] 2016-11-21 19:16
Yes, I could... except there are thousands of devices with only PTR records or mismatched PTR records.
Ultimately, i guess this software does not - by design, tolerate anything other than perfect DNS, at least from what I can tell.

**Comment by Gorian** [comment] 2016-11-21 19:44
it's technically a holdover from Observium, as Adam is, um... picky and particular, to be nice about it. But, ideally you should be using proper DNS in any large environment, otherwise you will have more issues than just LibreNMS not liking hosts.... I've seen people get away with adding hosts by IP (maybe by selecting the force add option? I use DNS, so idk) , but you really should be use DNS for a whole number of reasons...

**Comment by murrant** [comment] 2016-11-23 13:03
You could also modify your local install.

**Comment by athompso** [comment] 2016-11-23 17:31
We're now in the painful process of auditing five /21s worth of DNS.  Thankfully, not all of them have orphan PTR records...

**Comment by laf** [comment] 2017-02-04 18:28
I believe this is fixed with #5526 

Make sure you have `$config['discovery_by_ip'] = true;` set

**Closed by laf** 2017-02-04 18:28 UTC
Labels: Needs-Info
