### ISSUE TITLE
Test-Button for E-Mail does not work

### ISSUE THREAD

**Issue by fran-nlt** [librenms/librenms#1758] opened 2015-08-25 12:48 UTC
Hi
I am new in the community.
I download LibreNMS (VMDK) yesterday and config this it.
I enable Alert Settings in the Glogal Section and the config Email Transport but dont reciabe alert when interfaces down.

Thanks

**Comment by f0o** [comment] 2015-08-25 13:27
Hi,
Do you have any rules defined?

**Comment by fran-nlt** [comment] 2015-08-25 13:31
yes,all the default the system

Port status up/down	%macros.port_down = "1"

**Comment by fran-nlt** [comment] 2015-08-25 14:51
why is the default engine for the mail?

**Comment by laf** [comment] 2015-08-25 15:30
@fran-nlt on the image a mail server is installed (postfix or exim - can't remember), however all you need to do is use sendmail with the path /usr/sbin/sendmail (the default).

Set a default email address in the webui settings and click test transport next to the mail one.

**Comment by fran-nlt** [comment] 2015-08-25 15:45
I click in this button but nothing happens

From de CLI, I write mail fmunoz@nltnetworks.com, Enter,  Enter and reciabe SPAM from root@ubuntu-librenms.....

**Comment by laf** [comment] 2015-08-25 16:47
@fran-nlt Have you configured a default contact under: /settings/sub=alerting/ in the webui? It wont send a test alert unless you have.

**Comment by fran-nlt** [comment] 2015-08-25 16:51
@laf Yes, Look it please

![captura](https://cloud.githubusercontent.com/assets/13962782/9473287/68289338-4b30-11e5-9eef-2e1f36e990de.PNG)

**Comment by laf** [comment] 2015-08-25 16:54
@fran-nlt as you've got smtp details configured, change from sendmail to smtp and re-test.

**Comment by fran-nlt** [comment] 2015-08-25 16:59
@laf nothing, I try three options mail, sendmail and smtp and don´t receive alert
Do you other idea?

**Comment by laf** [comment] 2015-08-25 18:06
I'll try and boot the vm image later and test

**Comment by fran-nlt** [comment] 2015-08-25 18:30
I Am receive alert the system when Port if down!!! but de Click Tranport not works

I am 2 question more
The TimeStamps of de Alert is incorrect, how to change?
The Alert could set 8x5 or 24x7 or Customizable Time?

**Comment by laf** [comment] 2015-08-25 20:17
@fran-nlt 

1. Check your timezone for PHP, MySQL and the web server.

2. You can created scheduled downtime but not reoccurring so at present this isn't possible.

**Comment by soakes** [comment] 2015-08-26 15:25
I can confirm that I also am experencing the same issue as the OP.  After you setup email alerts and try and test it using the button on the right side, it does nothing.  I have checked logs as well as the logs on the mail server to see if it even tried to connect but it doesn't.  

I have also tried the same as the OP i.e. tried severythig from smtp+smtpauth to just using sendmail to even trying just using mail cmd/php.  Nothing seems to work at least to generate a test mail.

I can also confirm that I have a default contact set.

I can confirm that the pushover test alerts works apart from the timestamp in the message is blank.
https://www.dropbox.com/s/3ktwfv6jtu3xsa0/2015-08-26%2016.15.56.png?dl=0
This maybe by design, im not sure but is what ive just seen.

I can also confirm that my timezone settings in php.ini file for apache2+cli are both set to

`; London, England, Europe`
`date.timezone = "Europe/London"`
`date.default_latitude = 51.500181`
`date.default_longitude = -0.12619`

I have not taken a machine/service offline yet to see if the alerts actully do send or not and wil update later when its not so busy around here.

HTH

Any more info you require, please let me know.  Thanks.

Simon

**Comment by anderiv** [comment] 2015-08-27 14:01
Ditto - newly-installed librenms, using a SMTP relay local to the librenms server. After clicking the "test transport" button, nothing happens.

**Comment by f0o** [comment] 2015-08-27 14:17
I'm renaming this issue.
The problem is the test-button which seems nonfunctional.

I'm going to fix it in #1772

**Comment by f0o** [comment] 2015-08-27 17:16
The test-button fix has been merged now, please retest it after your install updated

**Comment by fran-nlt** [comment] 2015-08-27 17:54
Thanks, I reinstall LibreNMS, give me a time please

**Comment by fran-nlt** [comment] 2015-08-27 19:18
I Try

**Comment by fran-nlt** [comment] 2015-08-27 19:24
Nothing.

I try send to email to CLI and the message "mailutils not installed"

**Comment by laf** [comment] 2015-08-27 21:09
I've just booted the vm image to test, all I've done from a clean install is git pull to get the latest code, set everything as you see in the screenshot (which was just default contact and from address), clicked test transport and get the following in the logs:

```bash
Aug  9 11:39:51 ubuntu-librenms postfix/master[6251]: daemon started -- version 2.11.0, configuration /etc/postfix
Aug  9 11:40:01 ubuntu-librenms postfix/master[6251]: reload -- version 2.11.0, configuration /etc/postfix
Aug 10 07:06:54 ubuntu-librenms postfix/master[1193]: daemon started -- version 2.11.0, configuration /etc/postfix
Aug 27 14:07:12 ubuntu-librenms postfix/master[1196]: daemon started -- version 2.11.0, configuration /etc/postfix
Aug 27 14:06:35 ubuntu-librenms postfix/pickup[1199]: EAC9563CFD: uid=33 from=<neil@lathwood.co.uk>
Aug 27 14:06:35 ubuntu-librenms postfix/cleanup[2006]: EAC9563CFD: message-id=<0db7bc1a6cf1d65a425e0d1089ed43d6@ubuntu-librenms>
Aug 27 14:06:35 ubuntu-librenms postfix/qmgr[1200]: EAC9563CFD: from=<neil@lathwood.co.uk>, size=531, nrcpt=1 (queue active)
Aug 27 14:06:37 ubuntu-librenms postfix/smtp[2008]: connect to ASPMX.L.GOOGLE.COM[2a00:1450:400c:c07::1a]:25: Network is unreachable
Aug 27 14:06:37 ubuntu-librenms postfix/smtp[2008]: EAC9563CFD: to=<neil@lathwood.co.uk>, relay=ASPMX.L.GOOGLE.COM[64.233.166.26]:25, delay=1.9, delays=0.02/0.01/1.3/0.59, dsn=2.0.0, status=sent (250 2.0.0 OK 1440709597 m4si970128wiy.16 - gsmtp)
```


![image](https://cloud.githubusercontent.com/assets/3941142/9533170/2d748c72-4d08-11e5-913e-9b4f1183d99f.png)

If you are still having issues then maybe where you are testing doesn't allow mail to be sent straight out and you have to use a smarthost.

**Comment by fran-nlt** [comment] 2015-08-28 13:34
READY!!!
I configure smarthost and setting alert email using smtp and receive the alert test.
I wait from de alert the port down, please one minute

**Comment by fran-nlt** [comment] 2015-08-28 13:47
:(
The alert test button works but don´t the alert when port down

I try the 3 options
ufff

**Comment by fran-nlt** [comment] 2015-08-28 13:51
I need change 
 	Issued critical alert for rule 'Port status up/down' to transport 'mail' for  	Issued critical alert for rule 'Port status up/down' to transport 'smtp'

**Comment by fran-nlt** [comment] 2015-08-28 14:01
I added in config.php

$config['alert']['transports']['smtp'] = true;
$config['alert']['transports']['mail'] = false;


I try now

**Comment by f0o** [comment] 2015-08-28 14:11
`$config['alert']['transports']['smtp'] = true;`
Wont work, it doesnt exist.

If the test works, then the alerts will too. If not your rule didnt trigger or similar.

**Comment by f0o** [comment] 2015-08-28 14:12
The transport for email, regardless of smtp/sendmail/... is called 'mail'. The settings are done in the UI and those define what to do with the mail.

**Comment by fran-nlt** [comment] 2015-08-28 14:24
dont work.

**Comment by fran-nlt** [comment] 2015-08-28 14:30
look it
![captura](https://cloud.githubusercontent.com/assets/13962782/9548622/e8618836-4d77-11e5-85fe-bdf68c7b4825.PNG)

when the alert setting by smtp the alert test works
when the alert setting by mail the alert test don´t works

In the image when alert setting by smtp dont triger alert if port down/up but when the alert setting by mail trigger the alert

**Comment by laf** [comment] 2015-08-28 14:37
I'd highly suggest you remove any config.php options related to alerting and just configure through the webui. As @f0o has said, if the test works then real alerts will work. If mail isn't getting through then it simply will be a config issue in LibreNMS or on your mail server.

Using mail (i.e /usr/sbin/sendmail) works fine out of the box of the VM image, I tested it last night

**Comment by fran-nlt** [comment] 2015-08-28 14:43
I reinstall the zero yesterday with guide installation for ubuntu

**Comment by fran-nlt** [comment] 2015-08-28 14:47
YES!
Finally it works!!!
![captura](https://cloud.githubusercontent.com/assets/13962782/9549053/654b1c0c-4d7a-11e5-8c2c-ddccb1a4ff41.PNG)

sorry for so many questions i am new in the librenms

How to change the time in the receive the mail

**Comment by f0o** [comment] 2015-08-28 14:55
What time? The timestamp is when the alert got triggered, I wouldnt falsify that

**Closed** 2015-08-28 14:54 UTC
Labels: WebUI

**Comment by fran-nlt** [comment] 2015-08-28 14:58
Sorry
The Alert is correct, i am Refered for Delay but search in the alerts rules and found the options

Thanks!!!!!
