### ISSUE TITLE
Poll FDB tables and allow searching for MAC addresses

### ISSUE THREAD

**Issue by aauvinet** [librenms/librenms#2398] opened 2015-11-06 11:11 UTC
Hello,
I have the same issue :+1: 
Poll FDB tables and allow searching for MAC addresses #1196

I have lot of Cisco switch, I need to find @mac of host / port / vlan , for exemple personal computer...

In observium, it's possible and it's very well.

see the picture

20151106 Rosiak:
Removed obs... picture

**Comment by Rosiak** [comment] 2015-11-06 16:50
Please don't post material from obs..., I've just removed the picture from your post.

**Comment by aauvinet** [comment] 2015-11-09 13:09
Ok, sorry

**Comment by SaaldjorMike** [comment] 2015-12-21 10:22
Closing this as this is a duplicate of #1196 which you also refer to yourself.

**Closed by SaaldjorMike** 2015-12-21 10:22 UTC
Labels: Duplicate

**Comment by aauvinet** [comment] 2015-12-21 10:24
Ok,
Excuse me for the duplicate.
