### ISSUE TITLE
Device Request: OW-SERVER: 1-Wire to Ethernet Server

### ISSUE THREAD

**Issue by SirMaple** [librenms/librenms#9548] opened 2018-12-15 20:22 UTC
Would love to have OW-SERVER added to LibreNMS.

Product details: https://www.embeddeddatasystems.com/OW-SERVER-1-Wire-to-Ethernet-Server-Revision-2_p_152.html
MIB: https://eds.zendesk.com/attachments/token/gqibmt8n4b7ooe0/?name=EDS_MIB_V1.8.mib

The MIB is also available in the Downloads section on the Product details page.

**Comment by laf** [comment] 2018-12-15 22:46
Thanks for the bug report or new device request, unfortunately you have not provided the information asked for in point 3 when you created this issue.

Please provide pastebin links to the information we need and we will re-open this issue.

**Comment by SirMaple** [comment] 2018-12-15 22:56
Sorry about that.

I think I got all the info needed:

Discovery - https://p.libren.ms/view/6ff6ae62
Poller Output - https://p.libren.ms/view/a2029484
snmpbulkwalk - https://p.libren.ms/view/f9c3e8de

**Comment by PipoCanaja** [comment] 2019-01-26 18:56
That is correct for now. Each and every 1wire device type must be manually discovered.

**Comment by PipoCanaja** [comment] 2019-01-26 19:53
Support for DS18B20 is now added, you can remove and reinstall:

./scripts/github-remove
./scripts/github-apply 9740

PipoCanaja

**Comment by SirMaple** [comment] 2019-01-26 20:17
Yes, I just have the DS18B20 sensors at this time.

I performed the github-remove and applied 9740 again but I'm not seeing any changes.

Let me know if you the output of any commands to help troubleshoot.

**Comment by PipoCanaja** [comment] 2019-01-26 21:48
Did you force a new discovery of the device ?

**Comment by SirMaple** [comment] 2019-01-27 16:16
I think I did.

Clicked the "Rediscover", ran the discovery.php script from the command line, and also deleted the device and re-added it.

**Comment by SirMaple** [comment] 2019-01-27 16:47
I changed the SNMP version from v2c to v1 and now it's graphing each sensor. I'll let it run for a few hours and make sure it's actually updating.

Is there a way to make the name of each sensor editable?

**Comment by PipoCanaja** [comment] 2019-01-27 19:12
Is there a way to set a name for each sensor ? If yes, please do it, and send me a new snmpwalk so I can get the value and use it.

**Comment by SirMaple** [comment] 2019-01-27 19:34
Ah well. I'm sure it will get added as a feature down the road. Best part about librenms is it's always being worked on :)

Sounds good. Let me know if you need anymore outputs. Thanks for all the work you put into this project.

**Comment by PipoCanaja** [comment] 2019-01-27 23:18
I have the values correctly discovered. Are you running a current version of LibreNMS ? 
![capture d ecran 2019-01-28 a 00 17 17](https://user-images.githubusercontent.com/38363551/51808281-3027e000-2292-11e9-9f9c-d7da36ece1a3.png)

**Comment by SirMaple** [comment] 2019-01-28 17:16
If I switch back to SNMPv2c all the sensors disappear. If I switch back to SNMPv1 they re-appear.

On the OW-SERVER the only options for SNMP are enable, agent port(161), and community(public). 

Also the State of the sensors in LibreNMS shows as "owNone".

![screenshot_2019-01-28 mirage home lan - librenms 1](https://user-images.githubusercontent.com/17034743/51853551-cd603400-22e5-11e9-808a-23574d9a46f0.png)

**Comment by SirMaple** [comment] 2019-01-28 17:47
Could it have to do with the fact that it's looking for sensor "9" twice?

Looks like there's also a ' missing after "COMMUNITY".

![screenshot_2019-01-28 mirage home lan - capture - librenms](https://user-images.githubusercontent.com/17034743/51855312-28942580-22ea-11e9-9f67-0299b27e2b4c.png)

**Comment by PipoCanaja** [comment] 2019-01-28 19:02
> If I switch back to SNMPv2c all the sensors disappear. If I switch back to SNMPv1 they re-appear.
> On the OW-SERVER the only options for SNMP are enable, agent port(161), and community(public).
Could you collect for both v1 and v2c:
- discovery.php -h DEVICE -v -d | ./pbin.sh 
- poller.php -h DEVICE 

And compare where the difference is ;) Cause I can't reproduce that issue from the snmpsim data (which is always v2c)

> Also the State of the sensors in LibreNMS shows as "owNone".
(that means they will disappear after next discovery cause discovery skips entries with owNone status). The funny question is why does the reply change to owNone ... I can't tell.

The issue might be with OID not increasing, I'll try to add an option in snmpwalk to ignore it and we'll see if it does it better.

**Comment by PipoCanaja** [comment] 2019-01-28 20:35
Could you try the same snmpwalk that had the "not increasing" issue and add the following option : 

**-Cc**
_Do not check whether the returned OIDs are increasing. Some agents (for example, agents for Laser-Jet printers) return OIDs out of order, but can complete the walk anyway. Other agents return OIDs that are out of order and can cause snmpwalk to loop indefinitely. By default, snmpwalk tries to detect this behavior and warns you when it encounters an agent acting illegally. Use -Cc to turn off this feature._

**Comment by PipoCanaja** [comment] 2019-01-28 21:36
@SirMaple 
The snmpwalk you provided when you opened this issue did not have that "oid not increasing" problem. (https://p.libren.ms/view/f9c3e8de). Did you upgrade the device in between ? Downgrade ? 
Any chance to get the vendor help on the issue to see what changed ?

**Comment by SirMaple** [comment] 2019-01-28 22:05
When I got the OW-SERVER a few years ago I installed the latest firmware and it looks like a new version hasn't been released since.

Outputs:

> SNMPv1 - ./discovery.php -h mirage.home.lan -v -d | ./pbin.sh -> https://p.libren.ms/view/2dbe6fd7

> SNMPv1 - ./poller.php -h mirage.home.lan | ./pbin.sh -> https://p.libren.ms/view/9ba05306

> SNMPv2c - ./discovery.php -h mirage.home.lan -v -d | ./pbin.sh -> https://p.libren.ms/view/6671225a

> SNMPv2c - ./poller.php -h mirage.home.lan | ./pbin.sh -> https://p.libren.ms/view/701ba064

snmpwalk with -Cc option:
>/usr/bin/snmpbulkwalk -v2c -c public -Cc -OteQUs -Ih -m EDS-MIB -M /opt/librenms/mibs/opt/librenms/mibs/eds udp:mirage.home.lan:161 owDS18B20Temperature
owDS18B20Temperature.0 = "00 "
owDS18B20Temperature.1 = "20.3125"
owDS18B20Temperature.2 = "-0.4375"
owDS18B20Temperature.3 = "0.2500"
owDS18B20Temperature.4 = "21.0000"
owDS18B20Temperature.5 = "47.0000"
owDS18B20Temperature.6 = "10.6250"
owDS18B20Temperature.7 = "40.8125"
owDS18B20Temperature.8 = "8.8750"
owDS18B20Temperature.9 = "20.8750"
owDS18B20Temperature.9 = "20.8750"
owDS18B20Temperature.10 = "20.5625"
owDS18B20Temperature.11 = "18.1250"
owDS18B20Temperature.12 = "20.7500"
owDS18B20Temperature.13 = "00 "
owDS18B20Temperature.14 = "00 "
owDS18B20Temperature.15 = "00 "
owDS18B20Temperature.16 = "00 "
owDS18B20Temperature.17 = "00 "
owDS18B20Temperature.18 = "00 "
Timeout: No Response from udp:mirage.home.lan:161

I checked in my Cacti install and I am polling with SNMPv2c but just polling the individual OID's and not using the MIB. I see that https://github.com/librenms/librenms/pull/8738 is in the works and I may just have to wait for that to be added.

**Comment by murrant** [comment] 2019-01-28 22:21
@SirMaple Thanks for that.  We need the `-d` on the poller script: `./poller.php -d -h mirage.home.lan | ./pbin.sh`  Can you re-run that?

**Comment by SirMaple** [comment] 2019-01-28 22:25
I must say that pbin.sh script sure makes life easy! 

Ouputs:

> SNMPv1 - ./poller.php -d -h mirage.home.lan | ./pbin.sh -> https://p.libren.ms/view/f7cb93eb

> SNMPv2c - ./poller.php -d -h mirage.home.lan | ./pbin.sh -> https://p.libren.ms/view/c0e4ec78

**Comment by murrant** [comment] 2019-01-28 22:30
Cute, it outputs 9 twice:
```
owDeviceIndex.9 = 9
owDeviceIndex.9 = 9
```

**Comment by murrant** [comment] 2019-01-28 22:49
@PipoCanaja 
What you expext:
```
owDS18B20Temperature.0 = "00 "
owDS18B20Temperature.1 = "17.5625"
owDS18B20Temperature.2 = "1.7500"
owDS18B20Temperature.3 = "2.0625"
owDS18B20Temperature.4 = "17.3750"
owDS18B20Temperature.5 = "17.4375"
owDS18B20Temperature.6 = "8.4375"
owDS18B20Temperature.7 = "46.3750"
owDS18B20Temperature.8 = "9.3125"
owDS18B20Temperature.9 = "19.8125"
owDS18B20Temperature.10 = "20.5000"
owDS18B20Temperature.11 = "17.1875"
owDS18B20Temperature.12 = "21.2500"
owDS18B20Temperature.13 = "00 "
owDS18B20Temperature.14 = "00 "
owDS18B20Temperature.15 = "00 "
owDS18B20Temperature.16 = "00 "
owDS18B20Temperature.17 = "00 "
owDS18B20Temperature.18 = "00 "
owDS18B20Temperature.19 = "00 "
owDS18B20Temperature.20 = "00 "
owDS18B20Temperature.21 = "00 "
owDS18B20Temperature.22 = "00 "
owDS18B20UserByte1.0 = 0
owDS18B20UserByte1.1 = 75
owDS18B20UserByte1.2 = 75
owDS18B20UserByte1.3 = 75
owDS18B20UserByte1.4 = 75
owDS18B20UserByte1.5 = 75
owDS18B20UserByte1.6 = 75
owDS18B20UserByte1.7 = 75
owDS18B20UserByte1.8 = 75
owDS18B20UserByte1.9 = 75
owDS18B20UserByte1.10 = 75
owDS18B20UserByte1.11 = 75
owDS18B20UserByte1.12 = 75
owDS18B20UserByte1.13 = 0
owDS18B20UserByte1.14 = 0
owDS18B20UserByte1.15 = 0
owDS18B20UserByte1.16 = 0
owDS18B20UserByte1.17 = 0
owDS18B20UserByte1.18 = 0
owDS18B20UserByte1.19 = 0
owDS18B20UserByte1.20 = 0
owDS18B20UserByte1.21 = 0
owDS18B20UserByte1.22 = 0
owDS18B20UserByte2.0 = 0
owDS18B20UserByte2.1 = 70
owDS18B20UserByte2.2 = 70
owDS18B20UserByte2.3 = 70
owDS18B20UserByte2.4 = 70
owDS18B20UserByte2.5 = 70
owDS18B20UserByte2.6 = 70
owDS18B20UserByte2.7 = 70
owDS18B20UserByte2.8 = 70
owDS18B20UserByte2.9 = 70
owDS18B20UserByte2.10 = 70
owDS18B20UserByte2.11 = 70
owDS18B20UserByte2.12 = 70
owDS18B20UserByte2.13 = 0
owDS18B20UserByte2.14 = 0
owDS18B20UserByte2.15 = 0
owDS18B20UserByte2.16 = 0
owDS18B20UserByte2.17 = 0
owDS18B20UserByte2.18 = 0
owDS18B20UserByte2.19 = 0
owDS18B20UserByte2.20 = 0
owDS18B20UserByte2.21 = 0
owDS18B20UserByte2.22 = 0
owDS18B20Resolution.0 = 0
owDS18B20Resolution.1 = 12
owDS18B20Resolution.2 = 12
owDS18B20Resolution.3 = 12
owDS18B20Resolution.4 = 12
owDS18B20Resolution.5 = 12
owDS18B20Resolution.6 = 12
owDS18B20Resolution.7 = 12
owDS18B20Resolution.8 = 12
owDS18B20Resolution.9 = 12
owDS18B20Resolution.10 = 12
owDS18B20Resolution.11 = 12
owDS18B20Resolution.12 = 12
owDS18B20Resolution.13 = 0
owDS18B20Resolution.14 = 0
owDS18B20Resolution.15 = 0
owDS18B20Resolution.16 = 0
owDS18B20Resolution.17 = 0
owDS18B20Resolution.18 = 0
owDS18B20Resolution.19 = 0
owDS18B20Resolution.20 = 0
owDS18B20Resolution.21 = 0
owDS18B20Resolution.22 = 0
owDS18B20PwrSupply.0 = 0
owDS18B20PwrSupply.1 = 255
owDS18B20PwrSupply.2 = 255
owDS18B20PwrSupply.3 = 255
owDS18B20PwrSupply.4 = 255
owDS18B20PwrSupply.5 = 255
owDS18B20PwrSupply.6 = 255
owDS18B20PwrSupply.7 = 255
owDS18B20PwrSupply.8 = 255
owDS18B20PwrSupply.9 = 255
owDS18B20PwrSupply.10 = 255
owDS18B20PwrSupply.11 = 255
owDS18B20PwrSupply.12 = 255
owDS18B20PwrSupply.13 = 0
owDS18B20PwrSupply.14 = 0
owDS18B20PwrSupply.15 = 0
owDS18B20PwrSupply.16 = 0
owDS18B20PwrSupply.17 = 0
owDS18B20PwrSupply.18 = 0
owDS18B20PwrSupply.19 = 0
owDS18B20PwrSupply.20 = 0
owDS18B20PwrSupply.21 = 0
owDS18B20PwrSupply.22 = 0

```

What you get:
```
owDS18B20Temperature.0 = "00 "
owDS18B20Temperature.1 = "21.6875"
owDS18B20Temperature.2 = "-0.3750"
owDS18B20Temperature.3 = "0.3125"
owDS18B20Temperature.4 = "22.6250"
owDS18B20Temperature.5 = "53.5000"
owDS18B20Temperature.6 = "11.6875"
owDS18B20Temperature.7 = "40.3750"
owDS18B20Temperature.8 = "10.6875"
owDS18B20Temperature.9 = "21.6875"
owDS18B20Temperature.9 = "21.6875"
owDS18B20Temperature.10 = "21.2500"
owDS18B20Temperature.11 = "18.1875"
owDS18B20Temperature.12 = "21.5625"
owDS18B20Temperature.13 = "00 "
owDS18B20Temperature.14 = "00 "
owDS18B20Temperature.15 = "00 "
owDS18B20Temperature.16 = "00 "
owDS18B20Temperature.17 = "00 "
owDS18B20Temperature.18 = "00 "
 
Error: OID not increasing: owDS18B20Temperature.9
 >= owDS18B20Temperature.9
```

So, in edition to 9 being duplicated, the table entries are returned out of order.

One work around would be only to walk the individual entries instead of the table.  So for temperatures: owDS18B20Temperature and pre-cache owDS18B20Resolution (or just check if the value = 00 instead of that)

**Comment by murrant** [comment] 2019-01-29 13:36
It could be yaml, but you would only get sensors up to index 18...

**Comment by PipoCanaja** [comment] 2019-01-29 20:03
@SirMaple We'll give the vendor some time to fix the issue. In the meantime, I would suggest to remove the part that fails and try to keep what works. 
I'll patch again to remove the failing sensors and get back to you for tests. Other option, if you have a spare devices that you could make accessible from outside, contact me.

**Comment by SirMaple** [comment] 2019-01-30 00:49
Unfortunately I just have the one device.

Let me know when you have a patch ready and I'll give it a test.

I had a thought, is it possible to not use the mib and just use OIDs if they're known? Perhaps with snmpget? 

For temperature the OIDs start at iso.3.6.1.4.1.31440.10.5.1.1.1 and increase the last number by 1. 

>iso.3.6.1.4.1.31440.10.5.1.1.1
iso.3.6.1.4.1.31440.10.5.1.1.2
iso.3.6.1.4.1.31440.10.5.1.1.3
iso.3.6.1.4.1.31440.10.5.1.1.4
iso.3.6.1.4.1.31440.10.5.1.1.5
and so on.

**Comment by PipoCanaja** [comment] 2019-01-30 10:05
This is not possible with YAML discovery, it has to read the table. We would need to move to PHP to do a loop. And without access to a device to test against, it will be a very long process of try and fail ... 
I would suggest that you do it and submit a PR and we can of course help you.

**Comment by PipoCanaja** [comment] 2019-01-30 10:49
@SirMaple 
Could you please check the patch once again ? I try to read the temperature table separately from the other tables, so the display should be slightly better, at least for the sensors below the duplicate entry (was .9 last time)

**Comment by SirMaple** [comment] 2019-01-30 10:56
Now I can leave mirage.home.lan using SNMPv2c and the sensors stay. However, they only show a temperature after the first discovery then when the poller runs they go back to zero.

Same goes for state, they all switch to owNone after the poller runs.

If I run the discovery again that also doesn't help.

I'm at a loss with what the heck is up with this thing.

**Comment by PipoCanaja** [comment] 2019-01-30 12:10
We made a progress here :) 

Please delete the device once again.
Then add it in SNMPv2 and run right away:
./discovery.php -d -v -h mirage.home.lan | ./pbin.sh 
./poller.php -d -v -h mirage.home.lan | ./pbin.sh

**Comment by murrant** [comment] 2019-01-31 04:33
@PipoCanaja the device might not handle multi-gets well...

**Comment by SirMaple** [comment] 2019-02-01 04:18
I deleted mirage.home.lan and re-added it using SNMPv2c and ran the commands right away.

Output:

> ./discovery.php -d -v -h mirage.home.lan | ./pbin.sh -> https://p.libren.ms/view/11c5ab87

> ./poller.php -d -v -h mirage.home.lan | ./pbin.sh -> https://p.libren.ms/view/1f1ca42f

**Comment by PipoCanaja** [comment] 2019-02-04 22:48
Hi @SirMaple 
The discovery looks as good as possible considering the funny SNMP behaviour of the device. It seems that the sensors are properly discovered. 
But there are multiple errors in the polling part during the RRD file creation. Could you check that aspect? 
@murrant : Is there a way to force from YAML to avoid snmp multi-get ? Or any other option ? 
Bye

**Comment by SirMaple** [comment] 2019-02-05 19:22
Oops. I was running the discovery and poller as my regular user. Errors are gone after running scripts using the librenms user.

Same issue. Temperatures show after discovery but disappear after the poller script runs.

Note that I did downgrade to ubuntu 16.04 so that my test vm matches my production vm.

Outputs:

> ./discovery.php -d -v -h mirage.home.lan | ./pbin.sh -> https://p.libren.ms/view/db454526

> ./poller.php -d -v -h mirage.home.lan | ./pbin.sh -> https://p.libren.ms/view/c5586e22

**Comment by SirMaple** [comment] 2019-02-08 00:39
I contacted the vendor early last week and followed up on Monday and sadly I haven't gotten a reply.

If I were to provide you with access to port 161 on the device would that make troubleshooting quicker? If so send my a private message on Discord(username is the same, SirMaple) with your source IP address and I'll open up the port and let you know my IP.

**Comment by PipoCanaja** [comment] 2019-02-09 23:56
Hi @murrant 

With direct access to @SirMaple's device, I think I got it. The snmpget OID is returned with a ".0" after :

> SNMP['/usr/bin/snmpget' '-v2c' '-c' 'public' '-OUQnte' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/eds' 'udp:xxxxxxxxx:161' '.1.3.6.1.4.1.31440.10.5.1.1.1' '.1.3.6.1.4.1.31440.10.5.1.1.2']
> .1.3.6.1.4.1.31440.10.5.1.1.1.0 = "20.2500"
> .1.3.6.1.4.1.31440.10.5.1.1.2.0 = "-21.0625" 

The table queried with snmpwalk is correct: 
> snmpwalk '-v2c' '-c' 'public' '-OUQnte' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/eds' 'udp:xxxxxxxxx:161' '.1.3.6.1.4.1.31440.10.5.1.1' 
> .1.3.6.1.4.1.31440.10.5.1.1.0 = "00 "
> .1.3.6.1.4.1.31440.10.5.1.1.1 = "20.5000"
> .1.3.6.1.4.1.31440.10.5.1.1.2 = "-20.4375"

and the OID queried with snmpwalk is wrong again: 
> snmpwalk '-v2c' '-c' 'public' '-OUQnte' '-M' '/opt/librenms/mibs:/opt/librenms/mibs/eds' 'udp:192.252.229.171:161' '.1.3.6.1.4.1.31440.10.5.1.1.1' 
> .1.3.6.1.4.1.31440.10.5.1.1.1**.0** = "20.5625"

I did use the includes/polling/sensors/state/eds.inc.php and includes/polling/sensors/temperature/eds.inc.php to workaround, by checking if the OID (added with ".0") is a key in the snmp_array. 

PR is coming.  

PipoCanaja

**Comment by SirMaple** [comment] 2019-02-10 00:20
This is great news. I'll test later tonight.

@PipoCanaja could you remove my IP address from the bottom snmpwalk. Much appreciated.

**Comment by PipoCanaja** [comment] 2019-02-13 08:13
Hi @SirMaple 
Done, the OW-Server device should now be discovered and polled, as the changes are now merged. You should remove the patch and upgrade your librenms to Master. 
Closing this. 
PipoCanaja

**Closed by PipoCanaja** 2019-02-13 08:13 UTC
Labels: Device :desktop_computer:
