### ISSUE TITLE
Thresholds are incorrectly assigned

### ISSUE THREAD

**Issue by theS1LV3R** [librenms/librenms#16242] opened 2024-07-25 16:31 UTC
### The problem

After polling a server using SNMP, the various thresholds (low, low warn, high, high warn) are incorrectly assigned. Example:

Discovering a fan results in the following data (captured in the debug view):
```
  25 => 
  array (
    'sensorNumber' => '65',
    'sensorReading' => '13440.000',
    'sensorPositiveHysteresis' => '0',
    'sensorNegativeHysteresis' => '0',
    'lncThreshold' => '0.000',
    'lcThreshold' => '420.000',
    'lnrThreshold' => '0.000',
    'uncThreshold' => '0.000',
    'ucThreshold' => '0.000',
    'unrThreshold' => '0.000',
    'eventAssertionEnable' => '4',
    'eventDeassertionEnable' => '4',
    'sensorIDString' => 'FAN1',
  ),
```

Importantly, notice that `lcThreshold` is set to `420`, while the rest are set to `0`.

In the discovery file for supermicro (`supermicro-bmc.yml`), we see the following:
```
low_warn_limit: lcThreshold
warn_limit: ucThreshold
low_limit: lnrThreshold
high_limit: unrThreshold
```

And this mapping is confirmed later in the discovery information:
```
Sensor fetched value: 13440.000  
FAN1: Cur 13440, Low: 0, Low Warn: 420, Warn: 0, High: 0
```

However, when looking in the `Health` tab of the device settings, the data is shown like this:
![image](https://github.com/user-attachments/assets/1f0f3541-fccf-4280-9ab1-d5542fb75f08)

Causing the "Sensor over limit" rule (defined as `sensors.sensor_current > sensors.sensor_limit AND sensors.sensor_alert = 1 AND macros.device_up = 1`) to trigger, even though the fan speed is completely OK.

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.5.0 (2024-06-16T22:06:42+02:00)
DB Schema | 2024_04_29_183605_custom_maps_drop_background_suffix_and_background_version (294)
PHP       | 8.2.20
Python    | 3.11.9
Database  | MariaDB 11.4.2-MariaDB-ubu2404
RRDTool   | 1.8.0
SNMP      | 5.9.4
===========================================

[OK]    Installed from package; no Composer required
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    No python wrapper pollers found
[OK]    Redis is functional
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Non-git install, updates are manual or from package
```

**Comment by murrant** [comment] 2024-07-26 01:54
It looks like LibreNMS is setting the correct limits as sent by the device.

**Comment by theS1LV3R** [comment] 2024-07-26 02:00
No? `lcThreshold` is 420, `low_warn_limit` uses `lcThreshold`, but LibreNMS stores it to "High warn" instead of "Low warn", as can be seen from the screenshot.

**Comment by murrant** [comment] 2024-07-26 02:06
Oh, I didn't look at the webui. Perhaps the labels are wrong in the webui?

**Comment by theS1LV3R** [comment] 2024-07-26 02:11
If it was only the label that was incorrect then it wouldn't trigger the alarm rule to trigger though I don't think. 

It's also correct for a lot of other sensors, both on this and other devices. It's just a couple devices that fail, mostly supermicro devices.

**Comment by murrant** [comment] 2024-07-26 02:24
I can't reproduce:
```
 array (
    'sensorNumber' => '71',
    'sensorReading' => '8500.000',
    'sensorPositiveHysteresis' => '0',
    'sensorNegativeHysteresis' => '0',
    'lncThreshold' => '700.000',
    'lcThreshold' => '500.000',
    'lnrThreshold' => '300.000',
    'uncThreshold' => '25300.000',
    'ucThreshold' => '25400.000',
    'unrThreshold' => '25500.000',
    'eventAssertionEnable' => '2580',
    'eventDeassertionEnable' => '2580',
    'sensorIDString' => 'FAN7',
  ),
```
```
FAN7: Cur 8500, Low: 300, Low Warn: 500, Warn: 25400, High: 25500
Discover sensor: .1.3.6.1.4.1.21317.1.3.1.2.16, sensorReading.16, supermicro-bmc, FAN7, snmp, 1, 1, , 8500, (limits: LL: 300, LW: 500, W: 25400, H: 25500), rrd_type = GAUGE  
```

![image](https://github.com/user-attachments/assets/8e0365c1-8959-4d30-8b28-2ece6289d7e3)

**Comment by theS1LV3R** [comment] 2024-07-30 13:43
Hm, that's interesting. For most of our Supermicro servers it works as intended, but some have this annoying issue...

What version of IPMI are you running on that server? Maybe there are some version differences?

This is the erroring version:
![image](https://github.com/user-attachments/assets/705df7a0-2f4b-4608-a676-efc39db0394e)
![image](https://github.com/user-attachments/assets/ae15ff8d-19a7-4a30-a18f-f5072d6328e6)


And here is the non-erroring version:
![image](https://github.com/user-attachments/assets/0c1a712b-9f5b-457a-8d55-52101fb76272)
![image](https://github.com/user-attachments/assets/5ca46b9c-f48d-4fab-89fb-5cabef513e04)


Maybe an issue in newer firmwares?

**Comment by theS1LV3R** [comment] 2024-07-30 13:55
Is there a away for me to see the exact SQL queries that are being done to insert the limits into the database? Using the discovery debug tool in the UI and the `discovery.php` script shows some `SELECT` statements, but no `INSERTS` :/

**Comment by murrant** [comment] 2024-08-25 15:22
There is probably no UPDATE statement because the limits match what is in the database.

Closing this because I could not find a defect in LibreNMS.  Feel free to re-open if you think that is still the case.

**Closed by murrant** 2024-08-25 15:22 UTC
