### ISSUE TITLE
Smokeping graphs do not show in librenms ping tab

### ISSUE THREAD

**Issue by gr0mit1** [librenms/librenms#1757] opened 2015-08-25 11:32 UTC
[2015-08-25 12:28]  <blahdeblah> gr0mit: BTW, found the issue with your smokeping graphs: $pings in /opt/librenms/html/includes/graphs/device/smokeping_all_common_avg.inc.php needs to be set the same as pings in /etc/smokeping/config.d/Database
[2015-08-25 12:29]  <blahdeblah> gr0mit: Drop us an issue about it at github and I'll get a patch sorted out

**Comment by f0o** [comment] 2015-08-27 10:43
Is this related to #1759 ?

**Comment by Rosiak** [comment] 2015-09-19 21:51
@gr0mit1 
Is this still a problem for you? 
Otherwise I'll close this issue.

**Comment by gr0mit1** [comment] 2015-09-22 07:56
Hi Søren

I'm still not seeing the ping graphs in the 'ping tab' of LibreNMS.  See
attached screenshot.

Either I'm doing something wrong, or the bug is still an issue.  Any
advice or pointers please?

Best Regards

Tim Robinson
TxRx Communications Ltd
+44 1256 810630

**Comment by paszczus** [comment] 2015-09-27 15:01
I have same problem i guess. Fresh install (first trym nice!) and grapgs are not shown. I have tested with lsof which folder is readed and it`s the proper one (/var/lib/smokeping)

**Comment by arrmo** [comment] 2015-12-10 16:52
Hi,

Also having issues here ... :(. I have set things up as outlined in http://docs.librenms.org/Extensions/Smokeping/ ... but no joy. BTW, that last line doesn't seem right in "Standard Smokeping" (which is what I'm trying) - is it? At least a semicolon is missing, but is that line needed?

Thanks!

**Comment by Rosiak** [comment] 2015-12-11 22:42
@librenms/reviewers 
If anyone got time, could you please go through the guide and verify that it's actually working?

**Comment by paszczus** [comment] 2015-12-11 22:48
It is working fine for me for month or so...

**Comment by arrmo** [comment] 2015-12-11 23:05
Hi,

It could be me, no argument there … ☺. But there definitely is an error in the online documentation. At least the last line is incorrect (if nothing else, semicolon needed … right?).

I have a working smokeping configuration, so don’t want LibreNMS to “mess” with that … ;-). So I just make the changes as follows (vs. the documentation) – adding these new lines to the bottom of /opt/librenms/config.php,

$config['smokeping']['dir'] = '/var/lib/smokeping';
$config['own_hostname'] => not using this line, as at least some syntax is wrong. What are you using for this line? And is 'own_hostname' = ‘localhost’?

This is all that needs to be changed, correct?

FYI, inside '/var/lib/smokeping' there are subdirectories … do you have this? I want them to be read, but I have also tried changing this to the path where the RRD files are directly – but still no joy.

Thoughts?

Thanks!

… Russell

**Comment by paulgear** [comment] 2015-12-12 00:25
If you're running Debian/Ubuntu, you might find this doc update from @thepacmanfan helpful: https://github.com/thepacmanfan/librenms/blob/master/doc/Extensions/Smokeping.md

**Comment by arrmo** [comment] 2015-12-12 03:02
Appreciate the link!

Arrgh – pulling my hair out though … ☹. Followed this link, and it adds all my LibreNMS machines to Smokeping – they work great, show up in Smokeping. But still no tab in LibreNMS – that part is what is broken.

Open to any ideas you have!

Thanks,
… Russell

**Comment by thepacmanfan** [comment] 2015-12-12 03:09
I ran into this a few times when testing for my documentation; I think it was always caused by not enabling integration in /opt/librenms/config.php
In my doc it's covered under the heading "Configure LibreNMS", near the end. Make sure 'dir' points to your actual smokeping data location!

**Comment by arrmo** [comment] 2015-12-12 03:16
Hi,

Yep, agree with you 100%! Really, for LibreNMS it seems only two lines are needed (the rest of the info is about SmokePing, and that is all working fine – data, graphs, etc.). Here is all I have added to /opt/librenms/config.php

$config['smokeping']['dir'] = '/var/lib/smokeping';
$config['smokeping']['integration'] = true;

And if I look at /var/lib/smokeping, I see all the data directories (not raw data, but others seem to point here also). But that said, I also tried appending the next level directory (down), where I see all the rrd files. Then refresh my web page – no joy … ☹. To confirm, it is supposed to add a tab up along the top, correct? Maybe I’m looking the wrong place.

Thanks for all the pointers!

… Russell

**Comment by thepacmanfan** [comment] 2015-12-12 03:22
It adds a tab when viewing a specific device. On Network devices, it's
between "Ports" and "Map". On Server devices it's between "Ports" and
"Virtual Machines".

**Comment by arrmo** [comment] 2015-12-12 03:26
Ah-ha! There’s the confusion (on my part) – sorry! When folks were referring to a tab, I thought that meant at the very top. Yes, I do see it lower down. But here’s the issue then … I want to do this to include devices that don’t support SNMP (I think that’s the point of this, no?).

So that said, how do I add a device that only has ping data (from SmokePing), no SNMP?

Thanks!

… Russell

**Comment by thepacmanfan** [comment] 2015-12-12 03:33
No idea if that's feasible, sorry! I'm a newbie to LibreNMS. I am using it
in a supplementary role for more thorough network diagnostic information
than SNMP provides. All the hosts I'm using it for support SNMP, and I'm
graphing a lot more than just smokeping data.

**Comment by arrmo** [comment] 2015-12-12 03:40
Makes sense, much appreciated! I’m new to LibreNMS as well, but really like it. Let’s see if others have added machines that are ping-only.

Thanks again,
… Russell

**Comment by paulgear** [comment] 2015-12-12 06:54
@arrmo There's currently no interface to view the non-SNMP hosts from your statically-defined hosts in smokeping.
P.S. When you reply to these threads via email, please trim the original email or use Usenet-style quoting.  Otherwise it makes the github thread very noisy.

**Comment by Rosiak** [comment] 2015-12-12 12:44
Closing this one, documentation has been updated #2610

**Closed by Rosiak** 2015-12-12 12:44 UTC

**Comment by arrmo** [comment] 2015-12-12 12:49
Will do on the trimming, sorry! Some folks like the history, but understood – thanks for the pointer. And thanks so much for all the help, sorry for the confusion on my part.

FYI, it would be nice at some point to provide this capability, as many hosts are ping only, and it would be helpful to have all the hosts in one tool.

And perhaps update the online documentation? As noted in the thread, that last line isn’t quite right.

Thanks again!!!

… Russell

**Comment by laf** [comment] 2015-12-12 12:59
@arrmo 
We have an open issue to add non-snmp device support.

As for the docs, feel free to contribute when you see issues :)

**Comment by arrmo** [comment] 2015-12-12 19:15
Sounds great, thanks! If you have some WIP for ping, let me know – more than happy to check it out.

And on the documentation – I’ll go in and update it. I didn’t realize I’d be able to mess with it, but will do.

Thanks again!
