### ISSUE TITLE
Generic devices from poller

### ISSUE THREAD

**Issue by ladeth** [librenms/librenms#3218] opened 2016-03-11 08:48 UTC
I have a central LibreNMS server (hosting Mysql database, RRD directories and Web Interface). This server is also localy polling few firewalls. All is working fine on this server.

I also have a distributed poller, which is dedicated to cisco and brocade switches polling. On this poller, the devices are correctly recognized after `/opt/librenms/addhost.php -g 1 hosttobeadded community v2c`, `/opt/librenms/discovery.php -h hosttobeadded` and `/opt/librenms/cronic /opt/librenms/poller-wrapper.py 16` commands. 

My devie is displayed on the web interface, the vendor icon is Cisco logo, hardware is catalyst2960G24 and operating system is **Cisco IOS 12.2(53)SE1 (LANBASEK9)**. The crontab is running all the day and values are correctly populated in the database, graphs are correctly displayed and so on...

But, each night, when the crontab task "`33  */6   * * *   librenms    /opt/librenms/discovery.php -h all >> /dev/null 2>&1`" is launched, my device lost some informations. The operating system becomes **Generic Device 12.2(53)SE1**, the device logo is now Generic.

I've tried to launch again the command `/opt/librenms/discovery.php -h hosttobeadded` and the operating system is now again well recognized as **Cisco IOS 12.2(53)SE1 (LANBASEK9)** but the logo is still Generic device.

This issue only occures on my poller for any device polled on it. I don't have the same issue for the devices polled by the central server.

**Comment by laf** [comment] 2016-03-15 23:53
Please look through the eventlog for that specific device in the webui to see what it's recording on the OS being changed.

**Comment by murrant** [comment] 2016-03-18 21:40
Duplicate of #3236

**Closed by murrant** 2016-03-18 21:40 UTC
Labels: Needs-Info
