### ISSUE TITLE
Interface Type Sophos XG (Cyberoam)

### ISSUE THREAD

**Issue by thoms27** [librenms/librenms#8356] opened 2018-03-12 12:45 UTC
Hello,

I have the lastes version installed, and when I added a new device Sophos XG, discovered as Cyberoam, I have no media type and the interfaces of the firewall have been deleted : 
![image](https://user-images.githubusercontent.com/20238377/37284327-6a4e9272-25fb-11e8-9d91-06b8ad75841b.png)

Bellow the config.php filter : 
unset($config['bad_if']);
$config['bad_if'][] = 'voip-null';
$config['bad_if'][] = 'virtual-';
$config['bad_if'][] = 'unrouted';
$config['bad_if'][] = 'eobc';
$config['bad_if'][] = 'lp0';
$config['bad_if'][] = 'faith0';
$config['bad_if'][] = 'container';
$config['bad_if'][] = 'async';
$config['bad_if'][] = 'plip';
$config['bad_if'][] = '-physical';
$config['bad_if'][] = 'container';
$config['bad_if'][] = 'unrouted';
$config['bad_if'][] = 'bluetooth';
$config['bad_if'][] = 'isatap';
$config['bad_if'][] = 'ras';
$config['bad_if'][] = 'qos';
$config['bad_if'][] = 'span rp';
$config['bad_if'][] = 'span sp';
$config['bad_if'][] = 'sslvpn';
$config['bad_if'][] = 'pppoe-';
//$config['bad_if'][] = '-aal5';
$config['bad_if'][] = '-atm';

unset($config['bad_iftype']);
$config['bad_iftype'][] = 'voiceEncap';
$config['bad_iftype'][] = 'voiceFXO';
$config['bad_iftype'][] = 'voiceFXS';
$config['bad_iftype'][] = 'voiceOverAtm';
$config['bad_iftype'][] = 'voiceOverFrameRelay';
$config['bad_iftype'][] = 'voiceOverIp';
$config['bad_iftype'][] = 'ds0';
$config['bad_iftype'][] = 'ds1';
$config['bad_iftype'][] = 'ds3';
$config['bad_iftype'][] = "isdn";     #show signaling traffic
$config['bad_iftype'][] = "lapd";      #show signaling traffic
$config['bad_iftype'][] = 'sonet';
//$config['bad_iftype'][] = 'aal5';
$config['bad_iftype'][] = 'atm';

$config['bad_iftype'][] = 'shdsl';
//$config['bad_iftype'][] = 'mpls';

Have you an idea how to allow the interface PortA to PortF ?

Thanks in advance.

Regards,

Thomas V.

**Comment by sorano** [comment] 2018-03-12 13:23
Hello @thoms27 

This is not a bug or a new device request.

Please close this github issue and ask on community site or discord instead.

**Closed** 2018-03-13 13:48 UTC
