### ISSUE TITLE
[Feature Request] Scheduled downtime / recurring maintenance window

### ISSUE THREAD

**Issue by FTBZ** [librenms/librenms#4847] opened 2016-10-21 06:02 UTC
When checking services with Nagios Plugins, many services are down a few minutes during the backup window. It will be awesome to be able to schedule a recurring maintenance window for operations like backup or recurring planned maintenance.

**Comment by laf** [comment] 2016-10-21 14:43
Duplicate of #4480.

If it's missing any info please add to that issue.

**Closed** 2016-12-13 09:33 UTC
Labels: Duplicate
