### ISSUE TITLE
Host UP mark as DOWN

### ISSUE THREAD

**Issue by tboulogne** [librenms/librenms#909] opened 2015-05-04 06:36 UTC
Hello,

I get a strange issue. I Disable an host to test the alerting system : i did not receive mail alert from this down host (mark down in GUI), but from another also mark down (but really UP).

Any tips to debug this please. I did not understand. Both host are check via check_mk and snmp.

Thanks for help.

**Comment by f0o** [comment] 2015-05-04 08:11
Hi,

can you provide us the rule that's triggering the alert please?

If possible, join the IRC so we can have a more realtime-ish debugging :)

**Comment by tboulogne** [comment] 2015-05-04 08:14
i just create the default rule :
http://prntscr.com/71c64l

Le 04/05/2015 10:11, Daniel Preussker a écrit :
>
> Hi,
>
> can you provide us the rule that's triggering the alert please?
>
> If possible, join the IRC so we can have a more realtime-ish debugging :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/librenms/librenms/issues/909#issuecomment-98624524>.
>

-- 
TNG CONCEPTS - Formation - Prestations Informatiques - Distribution 
<http://www.tng-concepts.com> 	
	
Mettre la Technologie au service de l'Homme.
Votre exigence. Notre Métier.
Thierry BOULOGNE
Responsable développement
(+33) 5 35 00 53 90 (Fixe)
(+33) 6 43 18 31 19 (Mob.)
Profil viadeo <http://fr.viadeo.com/fr/profile/thierry.boulogne2>

Formation - E-commerce - informatique
www.tng-concepts.com <http://www.tng-concepts.com>

**Comment by f0o** [comment] 2015-05-04 08:17
Which of these rules is triggering though?

**Comment by tboulogne** [comment] 2015-05-04 08:18
The down one

Le 04/05/2015 10:17, Daniel Preussker a écrit :
>
> Which of these rules is triggering though?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/librenms/librenms/issues/909#issuecomment-98626240>.
>

-- 
TNG CONCEPTS - Formation - Prestations Informatiques - Distribution 
<http://www.tng-concepts.com> 	
	
Mettre la Technologie au service de l'Homme.
Votre exigence. Notre Métier.
Thierry BOULOGNE
Responsable développement
(+33) 5 35 00 53 90 (Fixe)
(+33) 6 43 18 31 19 (Mob.)
Profil viadeo <http://fr.viadeo.com/fr/profile/thierry.boulogne2>

Formation - E-commerce - informatique
www.tng-concepts.com <http://www.tng-concepts.com>

**Comment by f0o** [comment] 2015-05-04 08:22
ok, So just to be sure to be on the same page here:

You're getting Device-Down alerts (`%macros.device_down = "1"`) for a device that's actually showing up as UP in the GUI, right?

**Comment by tboulogne** [comment] 2015-05-04 08:24
exactly.

I shutdown an host to check the alert. I receive alert from another who 
is UP.

Le 04/05/2015 10:22, Daniel Preussker a écrit :
>
> ok, So just to be sure to be on the same page here:
>
> You're getting Device-Down alerts (|%macros.device_down = "1"|) for a 
> device that's actually showing up as UP in the GUI, right?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/librenms/librenms/issues/909#issuecomment-98630649>.
>

-- 
TNG CONCEPTS - Formation - Prestations Informatiques - Distribution 
<http://www.tng-concepts.com> 	
	
Mettre la Technologie au service de l'Homme.
Votre exigence. Notre Métier.
Thierry BOULOGNE
Responsable développement
(+33) 5 35 00 53 90 (Fixe)
(+33) 6 43 18 31 19 (Mob.)
Profil viadeo <http://fr.viadeo.com/fr/profile/thierry.boulogne2>

Formation - E-commerce - informatique
www.tng-concepts.com <http://www.tng-concepts.com>

**Comment by f0o** [comment] 2015-05-04 08:27
That's very odd, I cant reproduce this on my environment..

Can you run this SQL and compare the actual results with the ones you expect please?

`SELECT device_id,status,hostname FROM devices WHERE status = 0`

This should only print devices that are DOWN for LibreNMS. If the device that causes alerts is among the results, the issue may be with polling.

**Comment by tboulogne** [comment] 2015-05-04 08:32
agree with you ! very odd. For information, i think like you it's a polling problem. I delete the host and recreate it. And get same result.

For now, i shutdown an host and will past your sql. And let you know.

**Comment by f0o** [comment] 2015-05-04 08:35
Can you also run this please:
`/opt/librenms/poller.php -h <HOSTNAME>` ?
Replace <HOSTNAME> with the device's hostname.

Maybe it's something simple like ICMP-reject or SNMP-authproblem...

**Comment by tboulogne** [comment] 2015-05-04 08:40
````
+-----------+--------+------------+
| device_id | status | hostname   |
+-----------+--------+------------+
|         1 |      1 | localhost  |
|         2 |      0 | cronmaster |
|         3 |      1 | raidfox8   |
|         5 |      1 | mx2        |
|         6 |      1 | proxy2     |
|         7 |      0 | ope8       |
+-----------+--------+------------+
````

i a first time, i get only cronmaster down. A few minutes later, i get ope8 and receive a mail from ope8, not cronmaster.

result of poll:
````
/opt/librenms/poller.php -h ope8
LibreNMS 2014.master Poller

Starting polling run:

ope8 7 linux (unix)
SNMP Unreachable #1: NOCHG  #2: NOCHG  #3: NOCHG  #4: NOCHG  #5: NOCHG  #6: NOCHG  #7: NOCHG  #8: NOCHG

MySQL: Cell[1/0s] Row[10/0s] Rows[10/0s] Column[0/0s] Update[0/0s] Insert[1/0s] Delete[0/0s]
````
````
/opt/librenms/poller.php -h cronmaster
LibreNMS 2014.master Poller

Starting polling run:

cronmaster 2 linux (unix)
Unpingable #1: NOCHG  #2: NOCHG  #3: NOCHG  #4: NOCHG  #5: NOCHG  #6: NOCHG  #7: NOCHG  #8: NOCHG

MySQL: Cell[1/0s] Row[10/0s] Rows[9/0s] Column[0/0s] Update[0/0s] Insert[1/0s] Delete[0/0s]
````

**Comment by f0o** [comment] 2015-05-04 08:43
wow that looks wrong and not even a little bit wrong...

Please add '-d' to the poller.php's command and post the output

**Comment by tboulogne** [comment] 2015-05-04 08:55
let's go to debug :

````
/opt/librenms/poller.php -h cronmaster
LibreNMS 2014.master Poller

Starting polling run:

cronmaster 2 linux (unix)
Unpingable #1: NOCHG  #2: NOCHG  #3: NOCHG  #4: NOCHG  #5: NOCHG  #6: NOCHG  #7: NOCHG  #8: NOCHG

MySQL: Cell[1/0s] Row[10/0s] Rows[9/0s] Column[0/0s] Update[0/0s] Insert[1/0s] Delete[0/0s]
manager@monitor2:~$ /opt/librenms/poller.php -h cronmaster -d
LibreNMS 2014.master Poller

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'cronmaster' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '2']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '2'] cronmaster 2 linux (unix)
Unpingable
SQL[SELECT * FROM device_groups]
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '2' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT * FROM device_groups]
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '2' ) || alert_map.target = '2'  )]  #1:
SQL[SELECT state FROM alerts WHERE rule_id = '1' && device_id = '2' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '2') && ( ( devices.status = "0"  &&   ( devices.disabled = "0"  &&  devices.ignore = "0" )  )  = "1")]  NOCHG  #2:
SQL[SELECT state FROM alerts WHERE rule_id = '2' && device_id = '2' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '2') && (devices.uptime < "300"  &&   ( devices.disabled = "0"  &&  devices.ignore = "0" )  = "1")]  NOCHG  #3:
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '2' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM bgpPeers,devices WHERE (bgpPeers.device_id = devices.device_id && bgpPeers.device_id = '2') && (bgpPeers.bgpPeerState != "established"  &&   ( devices.status = "1"  &&   ( devices.disabled = "0"  &&  devices.ignore = "0" )  )  = "1")]  NOCHG  #4:
SQL[SELECT state FROM alerts WHERE rule_id = '4' && device_id = '2' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM bgpPeers WHERE (bgpPeers.device_id = '2') && (bgpPeers.bgpPeerFsmEstablishedTime < "300"  &&  bgpPeers.bgpPeerState = "established")]  NOCHG  #5:
SQL[SELECT state FROM alerts WHERE rule_id = '5' && device_id = '2' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM ports WHERE (ports.device_id = '2') && ( ( ports.ifOperStatus = "down"  &&  ports.ifAdminStatus != "down"  &&   ( ports.deleted = "0"  &&  ports.ignore = "0"  &&  ports.disabled = "0" )  )  = "1")]  NOCHG  #6:
SQL[SELECT state FROM alerts WHERE rule_id = '6' && device_id = '2' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM ports WHERE (ports.device_id = '2') && ( (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 >= "80")]  NOCHG  #7:
SQL[SELECT state FROM alerts WHERE rule_id = '7' && device_id = '2' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM sensors WHERE (sensors.device_id = '2') && (sensors.sensor_current > sensors.sensor_limit)]  NOCHG  #8:
SQL[SELECT state FROM alerts WHERE rule_id = '8' && device_id = '2' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM sensors WHERE (sensors.device_id = '2') && (sensors.sensor_current < sensors.sensor_limit_low)]  NOCHG

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','cronmaster','1430729437.5288','4.106','1','monitor2\n')] /opt/librenms/poller.php cronmaster 2015-05-04 10:50:41 - 1 devices polled in 4.106 secs

MySQL: Cell[1/0s] Row[10/0s] Rows[9/0s] Column[0/0s] Update[0/0s] Insert[1/0s] Delete[0/0s]
````

````
 /opt/librenms/poller.php -h ope8 -d
LibreNMS 2014.master Poller

DEBUG!
Starting polling run:


SQL[SELECT `device_id` FROM `devices` WHERE `disabled` = 0 AND `hostname` LIKE 'ope8' ORDER BY `device_id` ASC]
SQL[SELECT * FROM `devices` WHERE `device_id` = '7']
SQL[SELECT * FROM devices_attribs WHERE `device_id` = '7'] ope8 7 linux (unix)
DEBUG: SNMP Auth options =  -v2c -c technogwad
/usr/bin/snmpget -v2c -c technogwad -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:ope8:161 sysObjectID.0
Timeout: No Response from udp:ope8:161.

DEBUG: SNMP Auth options =  -v2c -c technogwad
/usr/bin/snmpget -v2c -c technogwad -Oqv -m SNMPv2-MIB -M /opt/librenms/mibs udp:ope8:161 SNMPv2-SMI::enterprises.39165.1.1.0
Timeout: No Response from udp:ope8:161.

SNMP Unreachable
SQL[SELECT * FROM device_groups]
SQL[SELECT DISTINCT(alert_schedule.schedule_id) FROM alert_schedule LEFT JOIN alert_schedule_items ON alert_schedule.schedule_id=alert_schedule_items.schedule_id WHERE ( alert_schedule_items.target = '7' ) && NOW() BETWEEN alert_schedule.start AND alert_schedule.end LIMIT 1]
SQL[SELECT * FROM device_groups]
SQL[SELECT alert_rules.* FROM alert_rules LEFT JOIN alert_map ON alert_rules.id=alert_map.rule WHERE alert_rules.disabled = 0 && ( (alert_rules.device_id = -1 || alert_rules.device_id = '7' ) || alert_map.target = '7'  )]  #1:
SQL[SELECT state FROM alerts WHERE rule_id = '1' && device_id = '7' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '7') && ( ( devices.status = "0"  &&   ( devices.disabled = "0"  &&  devices.ignore = "0" )  )  = "1")]  NOCHG  #2:
SQL[SELECT state FROM alerts WHERE rule_id = '2' && device_id = '7' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM devices WHERE (devices.device_id = '7') && (devices.uptime < "300"  &&   ( devices.disabled = "0"  &&  devices.ignore = "0" )  = "1")]  NOCHG  #3:
SQL[SELECT state FROM alerts WHERE rule_id = '3' && device_id = '7' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM bgpPeers,devices WHERE (bgpPeers.device_id = devices.device_id && bgpPeers.device_id = '7') && (bgpPeers.bgpPeerState != "established"  &&   ( devices.status = "1"  &&   ( devices.disabled = "0"  &&  devices.ignore = "0" )  )  = "1")]  NOCHG  #4:
SQL[SELECT state FROM alerts WHERE rule_id = '4' && device_id = '7' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM bgpPeers WHERE (bgpPeers.device_id = '7') && (bgpPeers.bgpPeerFsmEstablishedTime < "300"  &&  bgpPeers.bgpPeerState = "established")]  NOCHG  #5:
SQL[SELECT state FROM alerts WHERE rule_id = '5' && device_id = '7' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM ports WHERE (ports.device_id = '7') && ( ( ports.ifOperStatus = "down"  &&  ports.ifAdminStatus != "down"  &&   ( ports.deleted = "0"  &&  ports.ignore = "0"  &&  ports.disabled = "0" )  )  = "1")]  NOCHG  #6:
SQL[SELECT state FROM alerts WHERE rule_id = '6' && device_id = '7' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM ports WHERE (ports.device_id = '7') && ( (  ( ports.ifInOctets_rate * 8 )  / ports.ifSpeed )  * 100 >= "80")]  NOCHG  #7:
SQL[SELECT state FROM alerts WHERE rule_id = '7' && device_id = '7' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM sensors WHERE (sensors.device_id = '7') && (sensors.sensor_current > sensors.sensor_limit)]  NOCHG  #8:
SQL[SELECT state FROM alerts WHERE rule_id = '8' && device_id = '7' ORDER BY id DESC LIMIT 1]
SQL[SELECT * FROM sensors WHERE (sensors.device_id = '7') && (sensors.sensor_current < sensors.sensor_limit_low)]  NOCHG

SQL[INSERT INTO `perf_times` (`type`,`doing`,`start`,`duration`,`devices`,`poller`)  VALUES ('poll','ope8','1430729508.1495','12.06','1','monitor2\n')] /opt/librenms/poller.php ope8 2015-05-04 10:52:00 - 1 devices polled in 12.06 secs

MySQL: Cell[1/0s] Row[10/0s] Rows[10/0s] Column[0/0s] Update[0/0s] Insert[1/0s] Delete[0/0s]
````

**Comment by f0o** [comment] 2015-05-04 09:00
Okay!
here's your problem: `Timeout: No Response from udp:ope8:161` (at least for ope8)
On cronmaster, it doesnt even attempt polling...

Can you verify that SNMPd is running on both devices and is accessable for LibreNMS?

if they're linux'es, you can `netstat -nplu` and check for a process called 'snmpd'.

Also check potential firewalls.

**Comment by f0o** [comment] 2015-05-04 09:01
netstat should return something like:
`udp        0      0 0.0.0.0:161             0.0.0.0:*                           26147/snmpd`

**Comment by tboulogne** [comment] 2015-05-04 09:05
snmpd is running smoothly :-(
````
udp        0      0 0.0.0.0:47611           0.0.0.0:*                           29065/snmpd
```

I just restart the host, and recheck

**Comment by f0o** [comment] 2015-05-04 09:09
It's running on port 47611 and not on 161!

You've to tell LibreNMS that it should use 47611 (go to the device-page, settings, SNMP, adjust port there)

**Comment by tboulogne** [comment] 2015-05-04 09:14
i send you the the output of ope8. Sorry.
But for information, after rebooting ope8, snmp works and the alert back to UP.

The odd question : until i shutdown cronmaster (no link with ope8), ope8 was showing up. Once, i shutdown cronmaster, get down alert on ope8. 

Strange isn't it ?

**Comment by f0o** [comment] 2015-05-04 09:21
:|
I think your install is haunted by daemons and dammed souls...

Jokes aside;
The hostnames do resolve correctly?
The devices do not conflict in IP addressing?
The SNMP ports are all correct? (above netstat showed 47611 whilest LibreNMS tried to poll 161)
What does `/opt/librenms/discovery.php -h <HOSTNAME> -d` report?
What does `nmap -p161 -sU -A -sC <HOSTNAME>` report?

Side-Question, Can you join the IRC? (http://webchat.freenode.net?channels=%23%23librenms for webclient)

**Comment by f0o** [comment] 2015-05-07 21:17
Marking as `invalid` until further information are provided.

**Comment by f0o** [comment] 2015-05-15 11:02
Closing due to inactivity, feel free to reopen if the error persists.

**Closed by f0o** 2015-05-15 11:02 UTC
Labels: Alerting, Invalid
