### ISSUE TITLE
librenms-service.py poller crash

### ISSUE THREAD

**Issue by ntaken** [librenms/librenms#12427] opened 2021-01-11 11:25 UTC
Hello!

Got this crash on the poller part of the service. After having runned librenms-service.py for little more than one hour.

Jan 11 10:36:41 srv-net101 librenms-service.py[1348043]: Poller_0-2(INFO):Completed poller run for 161 in 4.58s
Jan 11 10:36:41 srv-net101 librenms-service.py[1348043]: Traceback (most recent call last):
Jan 11 10:36:41 srv-net101 librenms-service.py[1348043]:   File "/opt/librenms/librenms-service.py", line 48, in <module>
Jan 11 10:36:41 srv-net101 librenms-service.py[1348043]:     service.start()
Jan 11 10:36:41 srv-net101 librenms-service.py[1348043]:   File "/opt/librenms/LibreNMS/service.py", line 404, in start
Jan 11 10:36:41 srv-net101 librenms-service.py[1348043]:     sleep(self.config.master_resolution)
Jan 11 10:36:41 srv-net101 librenms-service.py[1348043]:   File "/opt/librenms/LibreNMS/service.py", line 550, in reap
Jan 11 10:36:41 srv-net101 librenms-service.py[1348043]:     handler = signal(SIGCHLD, SIG_DFL)
Jan 11 10:36:41 srv-net101 librenms-service.py[1348043]:   File "/usr/lib/python3.8/signal.py", line 48, in signal
Jan 11 10:36:41 srv-net101 librenms-service.py[1348043]:     return _int_to_enum(handler, Handlers)
Jan 11 10:36:41 srv-net101 librenms-service.py[1348043]: TypeError: 'int' object is not callable
Jan 11 10:36:42 srv-net101 librenms-service.py[1348043]: Poller_0-5(INFO):Completed poller run for 117 in 4.12s
Jan 11 10:36:42 srv-net101 librenms-service.py[1348043]: Poller_0-18(INFO):Completed poller run for 169 in 6.33s
Jan 11 10:36:42 srv-net101 librenms-service.py[1348043]: Poller_0-12(INFO):Completed poller run for 385 in 4.30s
Jan 11 10:36:42 srv-net101 librenms-service.py[1348043]: Poller_0-8(INFO):Completed poller run for 100 in 4.49s
Jan 11 10:36:43 srv-net101 librenms-service.py[1348043]: Poller_0-13(INFO):Completed poller run for 298 in 4.23s
Jan 11 10:36:43 srv-net101 librenms-service.py[1348043]: Poller_0-1(INFO):Completed poller run for 433 in 3.69s
Jan 11 10:36:44 srv-net101 librenms-service.py[1348043]: Poller_0-19(INFO):Completed poller run for 65 in 4.09s
Jan 11 10:36:44 srv-net101 librenms-service.py[1348043]: Poller_0-3(INFO):Completed poller run for 601 in 4.98s
Jan 11 10:36:45 srv-net101 librenms-service.py[1348043]: Poller_0-9(INFO):Completed poller run for 603 in 5.37s
Jan 11 10:36:51 srv-net101 librenms-service.py[1348043]: Poller_0-11(WARNING):Polling device 134 unreachable, waiting 60s for retry
Jan 11 10:36:51 srv-net101 librenms-service.py[1348043]: Poller_0-11(INFO):Completed poller run for 134 in 13.53s
Jan 11 10:37:00 srv-net101 librenms-service.py[1348043]: Ping_0-1(INFO):Running fast ping
Jan 11 10:37:00 srv-net101 librenms-service.py[1348043]: Billing(INFO):Calculating billing
Jan 11 10:37:00 srv-net101 librenms-service.py[1348043]: Alerting(INFO):Checking alerts
Jan 11 10:37:01 srv-net101 librenms-service.py[1348043]: Billing(INFO):Completed billing run for calculate in 0.08s
Jan 11 10:37:01 srv-net101 librenms-service.py[1348043]: Alerting(INFO):Completed alerting run for alerts in 0.12s
Jan 11 10:37:13 srv-net101 librenms-service.py[1348043]: Ping_0-1(INFO):Completed ping run for  in 12.93s
Jan 11 10:38:00 srv-net101 librenms-service.py[1348043]: Ping_0-1(INFO):Running fast ping
Jan 11 10:38:00 srv-net101 librenms-service.py[1348043]: Billing(INFO):Calculating billing
Jan 11 10:38:00 srv-net101 librenms-service.py[1348043]: Alerting(INFO):Checking alerts
Jan 11 10:38:01 srv-net101 librenms-service.py[1348043]: Billing(INFO):Completed billing run for calculate in 0.09s
Jan 11 10:38:01 srv-net101 librenms-service.py[1348043]: Alerting(INFO):Completed alerting run for alerts in 0.12s
Jan 11 10:38:13 srv-net101 librenms-service.py[1348043]: Ping_0-1(INFO):Completed ping run for  in 13.03s
Jan 11 10:39:00 srv-net101 librenms-service.py[1348043]: Ping_0-1(INFO):Running fast ping
Jan 11 10:39:00 srv-net101 librenms-service.py[1348043]: Billing(INFO):Calculating billing
Jan 11 10:39:00 srv-net101 librenms-service.py[1348043]: Alerting(INFO):Checking alerts

After this the Poller part stopped working but the rest of the service seems to have continued working.

I had to restart the service to get polling working again.

====================================
Component | Version
--------- | -------
LibreNMS  | 1.70.1-29-g80ac2390c
DB Schema | 2020_10_12_095504_mempools_add_oids (191)
PHP       | 7.4.3
Python    | 3.8.5
MySQL     | 10.3.25-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.0.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

**Comment by ntaken** [comment] 2021-01-11 13:39
Crash again. And watchdog seems unable to restart the poller. note that I lowered number of workers to 16 but all other polling settings are the default.

Jan 11 14:02:40 srv-net101 librenms-service.py[2243555]: Poller_0-2(INFO):Completed poller run for 123 in 4.20s
Jan 11 14:02:41 srv-net101 librenms-service.py[2243555]: Traceback (most recent call last):
Jan 11 14:02:41 srv-net101 librenms-service.py[2243555]:   File "/opt/librenms/librenms-service.py", line 48, in <module>
Jan 11 14:02:41 srv-net101 librenms-service.py[2243555]:     service.start()
Jan 11 14:02:41 srv-net101 librenms-service.py[2243555]:   File "/opt/librenms/LibreNMS/service.py", line 404, in start
Jan 11 14:02:41 srv-net101 librenms-service.py[2243555]:     sleep(self.config.master_resolution)
Jan 11 14:02:41 srv-net101 librenms-service.py[2243555]:   File "/opt/librenms/LibreNMS/service.py", line 550, in reap
Jan 11 14:02:41 srv-net101 librenms-service.py[2243555]:     handler = signal(SIGCHLD, SIG_DFL)
Jan 11 14:02:41 srv-net101 librenms-service.py[2243555]:   File "/usr/lib/python3.8/signal.py", line 47, in signal
Jan 11 14:02:41 srv-net101 librenms-service.py[2243555]:     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
Jan 11 14:02:41 srv-net101 librenms-service.py[2243555]: TypeError: 'int' object is not callable

**Comment by chancez** [comment] 2021-02-22 18:30
I hit this bug too. I don't think this is a "support-request", this is a straight up bug. It's incorrectly handling signals.

**Comment by murrant** [comment] 2021-02-22 19:40
@chancez bug appears to be in the file /usr/lib/python3.8/signal.py,  However, if you have a workaround for the python bug, I'm all ears.

**Comment by murrant** [comment] 2021-02-22 19:49
https://bugs.python.org/issue39169 seems to illustrate the bug.

**Comment by murrant** [comment] 2021-02-22 19:52
@TheMysteriousX could we perhaps use a lock to prevent multiple threads from calling signal concurrently?

**Comment by chancez** [comment] 2021-02-22 20:14
Yeah I've been looking at the python issues quite a bit on this and it should be fixed in all versions of 3.8 so im a bit unsure if it's been fixed or not. It seems that the bug itself is primarily an issue when a signal handler isn't registered. Perhaps librenms could add a signal handler?

**Comment by chancez** [comment] 2021-02-22 20:18
It seems the original issue was similar, but slightly different. I believe https://github.com/python/cpython/pull/8920 might be the real fix for this particular bug.

**Comment by murrant** [comment] 2021-02-23 01:21
The ign2ndsig.py script still fails on Python 3.9.1

**Comment by TheMysteriousX** [comment] 2021-02-23 02:45
I'm scratching my head at this one a bit - we shouldn't be able to cause a crash inside the python standard library.

The only way I can see it crashing like this is if SIG_DFL is being set to None. Which is easy to detect, but how on earth is that happening?

**Comment by murrant** [comment] 2021-02-23 21:25
@TheMysteriousX To trigger it more relibably, set the maintenance schedule to 15s or something :)

**Comment by TheMysteriousX** [comment] 2021-03-02 17:11
I've still been unable to reproduce this so far on my own system - there must be an additional component to this, perhaps CPU or some other resource contention.

If someone with the issue regularly can help out, what I'd like to see is this line added to signal.py in ```signal()``` (around line 47 on Python 3.8:
```
    print('handler: ', handler, 'signalnum: ', signalnum)
```

Then comment with the stack trace with the output of that line included, and around 100 lines of context from journald, including timestamps and PID's.

**Comment by TheMysteriousX** [comment] 2021-03-11 12:54
I've finally managed to reproduce this, and have a working theory on what's happening.

```
Mar 11 11:17:46 librenms-service.py[35416]: thread:  main handler:  <bound method Service.reap of <LibreNMS.service.Service object at 0x7f9d5eb89ca0>> signalnum:  Signals.SIGCHLD
Mar 11 11:17:46 librenms-service.py[35416]: main(DEBUG):Cycle done, going to sleep
Mar 11 11:17:47  librenms-service.py[35416]: thread:  main handler:  Handlers.SIG_DFL signalnum:  Signals.SIGCHLD
```

If:
* a signal is received
* and before it is fully handled the main thread goes to sleep
* and another signal is raised before it wakes 

The handler is re-entered unsafely. The code tries to avoid the handler being executed twice because signal handling is not thread safe, but it seems it's not enough in 3.5+ - the changes made mean that the check to see if something unsafe is about to happen is itself, unsafe.

I think the best option is to try a different approach to handling children, and see if its possible to get the children just to die on their own.

**Comment by rkojedzinszky** [comment] 2021-03-11 23:23
> I've finally managed to reproduce this, and have a working theory on what's happening.
> 
> ```
> Mar 11 11:17:46 librenms-service.py[35416]: thread:  main handler:  <bound method Service.reap of <LibreNMS.service.Service object at 0x7f9d5eb89ca0>> signalnum:  Signals.SIGCHLD
> Mar 11 11:17:46 librenms-service.py[35416]: main(DEBUG):Cycle done, going to sleep
> Mar 11 11:17:47 librenms-service.py[35416]: thread:  main handler:  Handlers.SIG_DFL signalnum:  Signals.SIGCHLD
> ```
> 
> If:
> 
> * a signal is received
> * and before it is fully handled the main thread goes to sleep
> * and another signal is raised before it wakes
> 
> The handler is re-entered unsafely. The code tries to avoid the handler being executed twice because signal handling is not thread safe, but it seems it's not enough in 3.5+ - the changes made mean that the check to see if something unsafe is about to happen is itself, unsafe.

Service.reap() is the signal handler, and in python operation, it may be delayed, not executed in C context. (https://docs.python.org/3/library/signal.html#execution-of-python-signal-handlers)

That means, there is no re-entrance, or such. The signal is handled with some delay, with safe context. The handler sets `reap_flag`, and it is done. Then, the main loop at a later point detects that flag, and behaves accordingly. During that process should another signal arise, the handler will be called again with some delay, but again: there is no re-entrance. I think, the problem was specifically this delayed signal handling and meanwhile clearing the handler, which is indeed a python bug.

> 
> I think the best option is to try a different approach to handling children, and see if its possible to get the children just to die on their own.

**Comment by rkojedzinszky** [comment] 2021-03-13 12:16
@TheMysteriousX @murrant any comments?

**Comment by TheMysteriousX** [comment] 2021-03-14 21:22
Just in case issues with the nightly reloading crop up again in future, minimal example that can be adapted for testing/tweaking:

child.py
--------
```python
#! /usr/bin/env python3
import time
import random
import sys

print('doing', flush=True)
time.sleep(random.randint(1,60))
print('done', flush=True)
sys.exit(0)
```

process.py
----------
```python
import os
import random
import signal
import subprocess
import sys
import time
import threading

# Comment out the signal handler below to generate zombies
signal.signal(signal.SIGCHLD, signal.SIG_IGN)

ts = []


def wait_for_threads():
    print('Waiting for threads')
    [x.join() for x in ts]
    print('Done Waiting')


for i, x in enumerate(range(random.randint(1, 10))):
    for j, x in enumerate(range(random.randint(1, 5))):
        t = threading.Thread(target=subprocess.check_call,
                             args=('./child.py',),
                             kwargs={'stdout': subprocess.DEVNULL, 'stderr': subprocess.STDOUT, 'start_new_session': True, 'close_fds': True}
                            )
        print(f'Staring thread {i + 1}/{j + 1}', flush=True)
        t.start()
        ts.append(t)
    time.sleep(5)
    print(f'Completed cycle {i + 1}')

print('Restarting parent', flush=True)

# Uncomment to simulate midnight data loss
# wait_for_threads()

python = sys.executable
sys.stdout.flush()
os.execl(python, python, *sys.argv)
```

**Comment by rkojedzinszky** [comment] 2021-03-14 22:21
I see, that eventually there is an execl in service.py. Then, the only way is to really wait for zombie processes, but, simply setting up the signal handler upon startup should do the job. As in my first patch.

So, to your process.py, adding the following eliminates zombie processes:
```
def sigchld(*args, **kwargs):
    while True:
        pid, ret = os.waitpid(-1, os.WNOHANG)
        if pid == 0:
            return
signal.signal(signal.SIGCHLD, sigchld)
```

**Closed** 2021-03-18 21:39 UTC
Labels: support-request
