### ISSUE TITLE
Eventlog created for Tranceiver when port is admin down

### ISSUE THREAD

**Issue by papage** [librenms/librenms#3068] opened 2016-02-23 10:57 UTC
Librenms reports in the eventlog the following:
"Dbm power Tx 0/0/2/2 - Transceiver Tx Power Sensor under threshold: -INF dBm (< -12.2185 dBm)"
even when port is admin down (shut).
The above message apperas every five minutes.This happens on Cisco ASR9001 and maybe other routers.

This message should not appear at all. Even if the port was admin operational "no shut", it should only appear once a day or once at all and not every five minutes.

**Comment by laf** [comment] 2017-01-22 18:19
Hi,

We are trying to tidy up old issues by working out which ones are still required or have not yet been resolved. If this issue should remain open - please update it with the latest debug information ensuring your install is up to date.

_TAG_TIDYUP

**Comment by laf** [comment] 2017-01-28 01:18
Duplicate of #1065

**Closed by laf** 2017-01-28 01:18 UTC
