### ISSUE TITLE
Device performance graph broken

### ISSUE THREAD

**Issue by vitalisator** [librenms/librenms#3114] opened 2016-02-29 08:19 UTC
on some devices the performance graph look like this:
http://imgur.com/n4wfk8o

SQL Data seems to be ok:
http://imgur.com/B3h67TM

in some cases the graph data become ok when I choose a bigger time range.
Have seen this issue since some days ago. Anything changed here?

ideas what could be broken?

**Comment by adammmmm** [comment] 2016-02-29 11:28
Same here, same issue on every device we have.

**Comment by laf** [comment] 2016-03-01 17:48
I've actually proposed we remove this feature and table due to shear volume of data it generates. MySQL just isn't designed for it.

**Comment by vitalisator** [comment] 2016-03-02 19:18
@laf what is the replacement for that?

**Comment by laf** [comment] 2016-03-03 12:48
No replacement it's just the current feature is a burden on MySQL and one of the causes for using up all innodb buffers. It's a good theory but doesn't work in practice.

**Comment by ekoyle** [comment] 2016-03-03 15:42
Would it be better to move the data to rrd's?

**Comment by paulgear** [comment] 2016-03-16 01:06
@ekoyle @vitalisator Ping data is present in RRD form at http://YOUR-LIBRENMS/graphs/type=device_ping_perf/device=YOUR_DEVICE/

**Comment by ekoyle** [comment] 2016-03-16 17:15
I was thinking of perf_times rather than device_perf.  Is there any chance
someone would want to alert on this?  If so, we should keep the most recent
result in the db; otherwise I agree that we should just drop the table,
especially since the data is already in an rrd.

I think we should consider the same treatment for perf_times (keep most
recent in db, put the rest into rrds iff someone wants the historical data).

**Comment by paulgear** [comment] 2016-03-20 07:13
We could easily add the latest times to MySQL.  I had planned to do this in a future version of data_update() (in includes/datastore.inc.php).  Alerting based on a ping (or poller) time over a particular threshold is certainly a useful feature that we should keep.

**Comment by laf** [comment] 2016-06-15 13:01
This issue was fixed a bit ago, closing.

**Closed by laf** 2016-06-15 13:01 UTC
