### ISSUE TITLE
Duplicated graphs for all devices

### ISSUE THREAD

**Issue by andrzejmaczka** [librenms/librenms#13527] opened 2021-11-17 10:59 UTC
### The problem

Probably after daily update in the overview of the Applications tab, the graphs have been duplicated for all devices (of course with the sign?) it also disappeared Docker apps
![image](https://user-images.githubusercontent.com/67277751/142187609-df4d1da0-4f6c-4f0f-8ee2-2dd18e84d677.png)
Green is OK, Red are duplicated
the same situation look like on the rest of application

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.11.0-12-gf8764ddcb
DB Schema | 2021_11_12_123037_change_cpwVcID_to_unsignedInteger (225)
PHP       | 7.4.14
Python    | 3.8.10
MySQL     | 10.3.31-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Composer Version: 2.1.12
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[INFO]  Detected Python Wrapper
[OK]    Connection to memcached is ok
```

### Anything in the logs that might be useful for us?

[2021-11-17 11:06:48] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-17 11:06:48] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-17 11:06:48] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-17 11:06:49] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-17 11:06:49] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-17 11:06:49] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-17 11:06:49] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-17 11:06:49] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-17 11:06:49] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-17 11:06:49] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-17 11:06:49] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}
[2021-11-17 11:06:49] production.ERROR: Class 'App\Action' not found {"exception":"[object] (Error(code: 0): Class 'App\\Action' not found at /opt/librenms/poller.php:145)
[stacktrace]
#0 {main}
"}

**Comment by murrant** [comment] 2021-11-17 14:11
Step 1: run `./daily.sh`

**Comment by murrant** [comment] 2021-11-17 14:32
That error is kind of baffling.  Before you update, can you run `ls /opt/librenms/app` and look for Action.php in there?

**Comment by murrant** [comment] 2021-11-17 15:26
Cannot reproduce, must be a local install issue...  pending feedback I'll close this.

**Comment by andrzejmaczka** [comment] 2021-11-17 15:28
ls /opt/librenms/app
Api         Application.php  Console  Exceptions  Guards  Jobs       Models         Observers  Policies  Providers           View
ApiClients  Checks.php       Events   Facades     Http    Listeners  Notifications  Plugins    Polling   StreamedOutput.php

**Comment by andrzejmaczka** [comment] 2021-11-17 15:28
no Action.php found

**Comment by murrant** [comment] 2021-11-17 15:29
@andrzejmaczka are your issues still persisting?  What version are you on? `git status`   The patch was reverted because of an issue with overwrite_ip.

**Comment by andrzejmaczka** [comment] 2021-11-17 15:31
21.11.0-12-gf8764ddcb

**Comment by andrzejmaczka** [comment] 2021-11-17 15:56
@murrant I updated libre again to 2f478d04c and it looks like it's back to normal, however I lost my previous data in application rrds

**Comment by murrant** [comment] 2021-11-17 18:07
@andrzejmaczka yeah, but that PR will be merged again with the fix to issues with overwrite_ip.  I don't know if your issue was related to that or not.  Perhaps you could test #13525 and see if the issue still occurs

**Closed** 2021-11-17 20:29 UTC
