### ISSUE TITLE
discovery appending vlan_id to the end of the SNMP community string

### ISSUE THREAD

**Issue by digitalpilotnm** [librenms/librenms#1064] opened 2015-05-19 04:08 UTC
The discovery program is appending the VLAN_ID to the end of the community string.

Attached is the debug output.

http://pastebin.com/embed_iframe.php?i=FPzV30Y3

**Comment by laf** [comment] 2015-05-19 20:34
This is by design. Is it causing you issues?

**Comment by digitalpilotnm** [comment] 2015-06-01 18:02
Yes its causing discovery to fail as the snmp community string being submitted to the device is now INVALID.

So it appears that if the SNMP community string contains a @ symbol then libreNMS's discovery walk code breaks.

I just changed my devices SNMP string from B1ah.@b2.pub   to  crBLAH.BLAH.pub
and things started to work.

Might have to be careful in the code on escaping strings or such since @ is a valid character for an SNMP community string

**Comment by f0o** [comment] 2015-06-08 09:57
I think that's by design. I dont really understand why one would append VLAN_ID@COMMUNITY to the snmp-credentials but that can be removed if the rest of the team feels the same.

**Comment by laf** [comment] 2015-06-08 10:29
We can't remove that, it is by design - at least for cisco based devices. It may need to some more validation on what device it is before issuing it but please don't just remove that support.

Something similar to this: https://thwack.solarwinds.com/thread/50830

**Comment by laf** [comment] 2016-10-08 22:49
No further discussion has in 20 months. Closing.

**Closed by laf** 2016-10-08 22:49 UTC
Labels: Discovery, Discussion
