### ISSUE TITLE
Unable to trigger memory Alert Rule

### ISSUE THREAD

**Issue by PdeNiet** [librenms/librenms#6209] opened 2017-03-16 14:12 UTC
Hi,

I have created an Alert Rule with the following characteristics:
%mempools.mempool_perc >= "10"

This rule will not trigger. Other rules like BGP or the CPU like:
%processors.processor_usage >= "90"

Work just fine, could there be an issue specific to mempools here?
If i look in my 'Health > Memory' tab there are plenty of entries above 10% utilisation which should have triggered the rule. Unfortunately i am not aware of any method to debug this.

Installation is up-to-date when doing a validate.php

Component | Version
--------- | -------
LibreNMS  | fea705b7f5186def55cf920276478913d444690a
DB Schema | 177
PHP       | 7.0.15
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2

[OK]    Database connection successful

DO NOT DELETE THIS INFORMATION.

Please read this information carefully.
GitHub issues is for bugs, please do not post issues asking for help or how to do X, Y or Z.
You can use our irc channel ##librenms on freenode to ask questions or our community site.
If you have a feature request please post this on our community site.

Please confirm each of the sections below by putting an x in the box like [x].

 Is your install up to date? Updating your install
Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
 [x]Please include all of the information between the ==================================== section of ./validate.php which you can run from the cli.
 [unrel]Please provide ALL info asked for here.
 [x]Please provide as much detail as possible.
 [x]Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by murrant** [comment] 2017-03-17 03:29
This seems to work for me.  Go to a device you expect the rule to be triggered on and click the gear -> Capture -> Alerts -> Run.

Paste the output here.

**Comment by PdeNiet** [comment] 2017-03-20 10:07
Hi Murrant,

I've run the Capture and noticed only the BGP rules are processed:
`Rule name: BGP Session down
Alert rule: %bgpPeers.bgpPeerState != "established" && %macros.device_up = "1"        
Alert query: SELECT * FROM bgpPeers,devices WHERE (( devices.device_id = bgpPeers.device_id ) && bgpPeers.device_id = ?) && (bgpPeers.bgpPeerState != "established"  &&   (  ( devices.status = 1  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1"        )
Rule match: no match

Rule name: BGP Session established
Alert rule: %bgpPeers.bgpPeerFsmEstablishedTime < "300" && %bgpPeers.bgpPeerState = "established" && %macros.device_up = "1"  
Alert query: SELECT * FROM bgpPeers,devices WHERE (( devices.device_id = bgpPeers.device_id ) && bgpPeers.device_id = ?) && (bgpPeers.bgpPeerFsmEstablishedTime < "300"  &&  bgpPeers.bgpPeerState = "established"  &&   (  ( devices.status = 1  &&   (  ( devices.disabled = 0  &&  devices.ignore = 0 )  )  )  )  = "1"  )
Rule match: no match


Found 1 transports to send alerts to.
Transport: mail`

I'm unsure why the memory rule isn't in there either.

![image](https://cloud.githubusercontent.com/assets/16667573/24095397/4d6119ee-0d5d-11e7-94cf-4ee6d75a4b7e.png)

**Comment by laf** [comment] 2017-03-20 10:11
Check you don't have that rule mapped to certain devices as I expect that's what's the cause here.

**Comment by PdeNiet** [comment] 2017-03-20 10:16
Hi Laf,

Thanks for the quick response.
My Rule-mapping is empty (Alerts > Rule Mapping).

This should then apply the rule to all devices right?
If i create a '%macros.device_up = "1"' rule the triggering works fine.

**Comment by PdeNiet** [comment] 2017-03-20 11:27
I created another entry for mem-usage with exactly the same ruleset which is showing up in running the alerts in capture. I suspect the first entry is somehow bugged.

**Comment by murrant** [comment] 2017-03-22 05:43
Odd, can we close this?  Sounds like you got it fixed.

**Comment by PdeNiet** [comment] 2017-03-23 09:07
Thanks for the assistance, although i'm unsure what is causing this, it's not a problem for me anymore due to replacing the entry. As far as i'm concerned the issue can be close.

**Closed** 2017-03-23 09:14 UTC
Labels: Needs-Info
