### ISSUE TITLE
Device Grouping - Explorer Tree View

### ISSUE THREAD

**Issue by doesterhuizen** [librenms/librenms#5148] opened 2016-12-12 06:59 UTC
Feature Request

Not sure if the following is on the road map but it would be quite helpful to group devices in the Explorer Tree View.

This could be done by having a Root(folder)called LibreNMS and to create sub folders underneath the Librenms root folder one could allow the user to right-click on the folder and select an option to create a subfolder.

Below is an example of how it could possibly look.

LibreNMS
    |____Sub folder1
        |______Sub Sub-folder1
             |________Device1
             |________Device2
ETC.

To add the device to the folder one could 
1. Have an option in the Device menu called Device Tree when you click the device tree option a window will open that has 2 frames in it, the frame on the left will have the above tree with LibreNMS as the root.
This where the user can build the tree structure. The 2nd frame on the right will contain all the devices to allow the user to add a device to a specific group you could allow the user to drag the device to the group.

The same idea could be used for services

![image](https://cloud.githubusercontent.com/assets/24517967/21090560/42f4ac0c-c049-11e6-9cd4-667fef055901.png)

**Comment by laf** [comment] 2016-12-12 08:10
Duplicate of #2393

**Closed by laf** 2016-12-12 08:10 UTC
