### ISSUE TITLE
Deleted devices either not deleting, or come back after deleting.

### ISSUE THREAD

**Issue by g43us** [librenms/librenms#3794] opened 2016-07-07 14:13 UTC
I have setup 3 new instances of LibreNMS on Ubuntu 16.04 within the past 2 days. Installation is fine. When I add several devices, I am not able to delete them. The Devices stay in the web UI. The RRD folders and files get deleted. 

After about 5 minutes the devices reappear. This has happened on all 3 setups. Devices were Cisco 2960 and 3560 switches, and a 1941 router.

**Comment by murrant** [comment] 2016-07-08 20:24
Duplicate of #3783

**Closed by murrant** 2016-07-08 20:24 UTC
