### ISSUE TITLE
Problem with CPU detection with a Dell R610

### ISSUE THREAD

**Issue by kakopedreros** [librenms/librenms#6177] opened 2017-03-12 04:06 UTC
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

validate.php
==========================================================
Component | Version
--------- | -------
LibreNMS  | 1d243c40c76d34a44b25237b9db00edc9bffd217
DB Schema | 176
PHP       | 5.3.3
MySQL     | 5.1.73
RRDTool   | 1.4.7
SNMP      | NET-SNMP 5.5
==========================================================

[OK]    Database connection successful

==========================================================

Using LibreNMS since September 2016, never it was able to display the number of CPU and cores correctly.

Only displays 6 processor and the graphics of the server not show the load, and maintaining a 1% of usage in a medium to heady use servers.

<img width="696" alt="captura de pantalla 2017-03-12 a las 00 55 33" src="https://cloud.githubusercontent.com/assets/4590300/23828869/9f3ca77e-06be-11e7-975d-c48b76c7f1e9.png">

**I have 4 Dell R610 with the following hardware configuration:**
2 x Intel(R) Xeon(R) CPU E5649 @ 2.53GHz Processor with 6 cores
64 GB RAM DDR3 - Synchronous Registered (Buffered)

**And with the following Software configuration:**
Xenserver 6.2.0-70446c Kernel 2.6.32.43-0.4.1.xs1.8.0.865.170810xen (i686)
Dell OpenManage Server Administrato 7.4.0
NET-SNMP version 5.3.2.2

**OpenManage info page:**
<img width="1048" alt="captura de pantalla 2017-03-12 a las 00 56 55" src="https://cloud.githubusercontent.com/assets/4590300/23828878/dd904382-06be-11e7-8b9f-736a85b10349.png">

**SNMP Capture:**
[r610_snmpwalk.txt](https://github.com/librenms/librenms/files/836280/r610_snmpwalk.txt)

**Discovery capture:**
[r610_discovery.txt](https://github.com/librenms/librenms/files/836281/r610_discovery.txt)

**Poller capture:**
[r610_poller.txt](https://github.com/librenms/librenms/files/836282/r610_poller.txt)

As an additional information, the virtual Machines running in this servers shows the same behavior.

**Dell R610 running Xenserver 6.2**
<img width="386" alt="captura de pantalla 2017-03-12 a las 01 25 16" src="https://cloud.githubusercontent.com/assets/4590300/23829013/cc0f068a-06c2-11e7-8dbf-f9265b11a3d2.png">

**Windows Virtual Machine, with 4 vCPU**
<img width="391" alt="captura de pantalla 2017-03-12 a las 01 25 43" src="https://cloud.githubusercontent.com/assets/4590300/23829015/d8e462e2-06c2-11e7-8d28-43fc6732eb28.png">

**Comment by murrant** [comment] 2017-03-12 20:21
@kakopedreros It looks like snmp reports 6 processors.  I'm guessing `cat /proc/cpuinfo` will show 6 as well.

This is correct.  Are you sure this isn't a VM with 6 virtual CPUs assigned?

Here is what is reported by your server via SNMP:
```
hrDeviceDescr.768 = GenuineIntel: Intel(R) Xeon(R) CPU           E5649  @ 2.53GHz
hrDeviceDescr.769 = GenuineIntel: Intel(R) Xeon(R) CPU           E5649  @ 2.53GHz
hrDeviceDescr.770 = GenuineIntel: Intel(R) Xeon(R) CPU           E5649  @ 2.53GHz
hrDeviceDescr.771 = GenuineIntel: Intel(R) Xeon(R) CPU           E5649  @ 2.53GHz
hrDeviceDescr.772 = GenuineIntel: Intel(R) Xeon(R) CPU           E5649  @ 2.53GHz
hrDeviceDescr.773 = GenuineIntel: Intel(R) Xeon(R) CPU           E5649  @ 2.53GHz
...
hrProcessorLoad.768 = 5
hrProcessorLoad.769 = 1
hrProcessorLoad.770 = 1
hrProcessorLoad.771 = 1
hrProcessorLoad.772 = 1
hrProcessorLoad.773 = 1
```

Here is what one of my systems shows:
```
hrDeviceDescr.196608 = GenuineIntel: Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz
hrDeviceDescr.196609 = GenuineIntel: Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz
hrDeviceDescr.196610 = GenuineIntel: Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz
hrDeviceDescr.196611 = GenuineIntel: Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz
...
hrProcessorLoad.196608 = 26
hrProcessorLoad.196609 = 28
hrProcessorLoad.196610 = 25
hrProcessorLoad.196611 = 27
```

**Comment by kakopedreros** [comment] 2017-03-14 21:30
Hi @murrant the command is executed in the phisical machine, not the VM. It's seems the XenServer only see 6 cores. In the execution of cat `/proc/cpuinfo `it show 6 cores, missing the other processor entirely. (screenshot of the last core)
<img width="824" alt="captura de pantalla 2017-03-14 a las 18 00 06" src="https://cloud.githubusercontent.com/assets/4590300/23922181/1c5f3b54-08e0-11e7-871c-4468b6375ad3.png">

In the same Operative System i have Dell OpenManage, an application who sees the 2 processors and the 12 cores.
<img width="1423" alt="captura de pantalla 2017-03-14 a las 17 58 39" src="https://cloud.githubusercontent.com/assets/4590300/23922156/0aacdace-08e0-11e7-9e11-f6a6237eebfa.png">

And execute the command `sudo sudo dmidecode -t 4` sow the two processor and its cores.
[dmidecode.txt](https://github.com/librenms/librenms/files/842684/dmidecode.txt)

In the documentation of Xenserver indicates the logic way to identify the official number of processors, cores and theards i executing the command xl info.
[xl_info.txt](https://github.com/librenms/librenms/files/842707/xl_info.txt)

**Comment by kakopedreros** [comment] 2017-03-14 22:14
In addition, using the OMSA extension for SNMP, it is added a lot of information regards the operative system.

The MIBS from OMSA:

_processorDeviceCoreCount_
`1.3.6.1.4.1.674.10892.1.1100.30.1.17`

_processorDeviceCoreEnabledCount_
`1.3.6.1.4.1.674.10892.1.1100.30.1.18`

_processorDeviceThreadCount_
`1.3.6.1.4.1.674.10892.1.1100.30.1.19`

shows the correct information! (two processor, 6 cores each, 12 threads each).
[OMSA_mibs_snmpwalk.txt](https://github.com/librenms/librenms/files/842877/OMSA_mibs_snmpwalk.txt)

Dell OpenManage
SNMP Reference Guide Version 7.3
[dell-opnmang-srvr-admin-v7.3_Reference Guide3_en-us.pdf](https://github.com/librenms/librenms/files/842884/dell-opnmang-srvr-admin-v7.3_Reference.Guide3_en-us.pdf)

**Comment by kakopedreros** [comment] 2017-03-14 22:21
```
[root@librenms mibs]# /usr/bin/snmpbulkwalk -v2c -c 'PsnmpUlS-61691b' -OQUs -m MIB-Dell-10892 -M /opt/librenms/mibs:/opt/Dell-OM-MIBS-840_A00/mibs udp:172.17.1.50:161 1.3.6.1.4.1.674.10892.1.1100.30.1
processorDevicechassisIndex.1.1 = 1
processorDevicechassisIndex.1.2 = 1
processorDeviceIndex.1.1 = 1
processorDeviceIndex.1.2 = 2
processorDeviceStateCapabilities.1.1 = 0
processorDeviceStateCapabilities.1.2 = 0
processorDeviceStateSettings.1.1 = enabled
processorDeviceStateSettings.1.2 = enabled
processorDeviceStatus.1.1 = ok
processorDeviceStatus.1.2 = ok
processorPortIndexReference.1.1 = 1
processorPortIndexReference.1.2 = 2
processorDeviceType.1.1 = deviceTypeIsCPU
processorDeviceType.1.2 = deviceTypeIsCPU
processorDeviceManufacturerName.1.1 = "Intel"
processorDeviceManufacturerName.1.2 = "Intel"
processorDeviceStatusState.1.1 = enabled
processorDeviceStatusState.1.2 = enabled
processorDeviceFamily.1.1 = deviceFamilyIsIntelXeon
processorDeviceFamily.1.2 = deviceFamilyIsIntelXeon
processorDeviceMaximumSpeed.1.1 = 3600
processorDeviceMaximumSpeed.1.2 = 3600
processorDeviceCurrentSpeed.1.1 = 2533
processorDeviceCurrentSpeed.1.2 = 2533
processorDeviceExternalClockSpeed.1.1 = 5860
processorDeviceExternalClockSpeed.1.2 = 5860
processorDeviceVoltage.1.1 = 1200
processorDeviceVoltage.1.2 = 1200
processorDeviceUpgradeInformation.1.1 = processorUpgradeIsBySocketLGA1366
processorDeviceUpgradeInformation.1.2 = processorUpgradeIsBySocketLGA1366
processorDeviceVersionName.1.1 = "Intel(R) Xeon(R) CPU           E5649  @ 2.53GHz Stepping 2"
processorDeviceVersionName.1.2 = "Intel(R) Xeon(R) CPU           E5649  @ 2.53GHz Stepping 2"
processorDeviceCoreCount.1.1 = 6
processorDeviceCoreCount.1.2 = 6
processorDeviceCoreEnabledCount.1.1 = 6
processorDeviceCoreEnabledCount.1.2 = 6
processorDeviceThreadCount.1.1 = 12
processorDeviceThreadCount.1.2 = 12
processorDeviceCharacteristics.1.1 = 4
processorDeviceCharacteristics.1.2 = 4
processorDeviceExtendedCapabilities.1.1 = 31
processorDeviceExtendedCapabilities.1.2 = 31
processorDeviceExtendedSettings.1.1 = 29
processorDeviceExtendedSettings.1.2 = 29
processorDeviceBrandName.1.1 = "Intel(R) Xeon(R) CPU           E5649  @ 2.53GHz"
processorDeviceBrandName.1.2 = "Intel(R) Xeon(R) CPU           E5649  @ 2.53GHz"
processorDeviceModelName.1.1 = "Model 44"
processorDeviceModelName.1.2 = "Model 44"
processorDeviceSteppingName.1.1 = "Stepping 2"
processorDeviceSteppingName.1.2 = "Stepping 2"
```

**Comment by laf** [comment] 2017-03-14 22:33
Please download and try and run this script:

https://raw.githubusercontent.com/librenms/librenms-agent/master/agent-local/dmi

See if that gives you the output you expect.

**Comment by kakopedreros** [comment] 2017-03-15 02:42
@laf here is it the script result:
[dmidecode_2.txt](https://github.com/librenms/librenms/files/843293/dmidecode_2.txt)

Previously i run `sudo dmidecode -t 4`:
[dmidecode.txt](https://github.com/librenms/librenms/files/843288/dmidecode.txt)

**Comment by murrant** [comment] 2017-03-15 03:27
Perhaps try a newer net-snmp to see if it corrects the ucd output.

**Comment by laf** [comment] 2017-03-15 09:18
Yeah I think unless snmpd can provide the correct output the only way forward after this is to add application support using `xl` (needs a feature request).

OMSA support doesn't seem worth it as we aren't interested in the processor / core count but the actual usage which we need from snmpd.

Closing this as it's not a bug in LibreNMS

**Closed by laf** 2017-03-15 09:18 UTC
Labels: Needs-Info

**Comment by kakopedreros** [comment] 2017-03-15 19:02
=(

Thanks, for the help. ;)

**Comment by kakopedreros** [comment] 2017-03-27 00:40
@murrant @laf 

In fact, the problem is Xenserver itself. It use a VM called "Dom0" to manage the hardware resources and coordinate the virtualization. This VM had only 6 virtual CPU assigned, and the SNMP agent deliver this info, not from the hardware host. The hypervisor, who had direct access to the hardware is not posible install SNMP or something similar.

Further reading indicates, others monitor system use a custom agent to collect the data and show a limited amount of information.
