### ISSUE TITLE
Force10 FW version 9.11+ invalid CPU

### ISSUE THREAD

**Issue by f0o** [librenms/librenms#7527] opened 2017-10-23 09:45 UTC
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

Essentially Dell changed the entire Chassis MIB for f10 switches in their recent FW.
We should use `DELL-NETWORKING-CHASSIS-MIB::dellNetCpuUtil5Min.stack.{1,2}.1` from now on.

I tried to mend it myself but it has been too long since I added stacked CPUs so I have to give up :/

**Comment by f0o** [comment] 2017-10-23 10:18
This seems to work for us, can somebody verify it?

```diff
diff --git a/includes/discovery/processors/dnos-ftos.inc.php b/includes/discovery/processors/dnos-ftos.inc.php
index ffd5834..a13111b 100644
--- a/includes/discovery/processors/dnos-ftos.inc.php
+++ b/includes/discovery/processors/dnos-ftos.inc.php
@@ -3,7 +3,16 @@ if ($device['os'] == 'dnos' || $device['os'] == 'ftos') {
     echo 'DNOS CPU: ';
     $descr = 'CPU';
 
-    if (preg_match('/.6027.1.3.[0-9]+$/', $device['sysObjectID'])) {
+
+    if (preg_match('/^9\.11.*$/', $device['version'])) {
+        echo 'Dell Networking MIB';
+        $stack_cpu = snmp_get($device, '.1.3.6.1.4.1.6027.3.26.1.3.1.0', '-OvQ');
+        for ($i = 1; $i <= $stack_cpu; $i++) {
+            $usage = str_replace(' percent', '', snmp_get($device, '.1.3.6.1.4.1.6027.3.26.1.4.4.1.5.2.'.$i.'.1', '-OvQ'));
+            discover_processor($valid['processor'], $device, '.1.3.6.1.4.1.6027.3.26.1.4.4.1.5.2.'.$i.'.1', $i, $device['os'], $descr, '1', $usage);
+        }
+        unset($stack_cpu);
+    } elseif (preg_match('/.6027.1.3.[0-9]+$/', $device['sysObjectID'])) {
         echo 'Dell S Series Chassis';
         $usage = str_replace(' percent', '', snmp_get($device, 'chStackUnitCpuUtil5Sec.1', '-OvQ', 'F10-S-SERIES-CHASSIS-MIB'));
         discover_processor($valid['processor'], $device, '.1.3.6.1.4.1.6027.3.10.1.2.9.1.2.1', '0', $device['os'], $descr, '1', $usage);
```

**Comment by asteen-nexcess** [comment] 2017-10-24 00:59
@f0o I can confirm that is working for me as well.

**Comment by f0o** [comment] 2017-10-24 06:33
@asteen-nexcess can you tell me a bit more about the HW you've tested it against?

Is it S or C series? Is it a stack?

I'd like to redefine the version check because now it's super static. Ideally I'd like to test against the stack OID but I dont know if it's present everywhere...

**Comment by asteen-nexcess** [comment] 2017-10-24 21:55
@f0o The only thing I have on hand right now is a S4810 running 9.11(2.5). I will have access to a few more S4810's in the next few weeks to test for stacks unless someone else gets to it first.

I did add a few things to get the memory pool working again, but someone will likely want to check this over. Looks like temperature is also broken in 9.11, but I'll see if I can add something there as well.

``` diff
diff --git a/includes/discovery/mempools/dnos-ftos.inc.php b/includes/discovery/mempools/dnos-ftos.inc.php
index 0f8ed181a..6c880fe91 100644
--- a/includes/discovery/mempools/dnos-ftos.inc.php
+++ b/includes/discovery/mempools/dnos-ftos.inc.php
@@ -5,7 +5,12 @@
 if ($device['os'] == 'dnos' || $device['os'] == 'ftos') {
     echo 'DNOS-MEMORY-POOL:  ';

-    if (preg_match('/.6027.1.3.[0-9]+$/', $device['sysObjectID'])) {
+    if (preg_match('/^9\.11.*$/', $device['version'])) {
+        $total = snmp_get($device, 'dellNetProcessorMemSize.stack.1.1', '-OvQU', 'DELL-NETWORKING-CHASSIS-MIB');
+        if (is_numeric($total)) {
+            discover_mempool($valid_mempool, $device, 0, $device['os'], 'Memory Utilization', '1', null, null);
+        }
+    } elseif (preg_match('/.6027.1.3.[0-9]+$/', $device['sysObjectID'])) {
         $total = snmp_get($device, 'chSysProcessorMemSize.1', '-OvQU', 'F10-S-SERIES-CHASSIS-MIB');
         if (is_numeric($total)) {
             discover_mempool($valid_mempool, $device, 0, $device['os'], 'Memory Utilization', '1', null, null);
```
``` diff 
diff --git a/includes/polling/mempools/dnos.inc.php b/includes/polling/mempools/dnos.inc.php
index e1397c189..9b1f91123 100644
--- a/includes/polling/mempools/dnos.inc.php
+++ b/includes/polling/mempools/dnos.inc.php
@@ -2,7 +2,11 @@

 // Code below was borrowed from 'powerconnect-cpu.inc.php'

-if (preg_match('/.6027.1.3.[0-9]+$/', $device['sysObjectID'])) {
+if (preg_match('/^9\.11.*$/', $device['version'])) {
+    $mempool['total'] = snmp_get($device, 'dellNetProcessorMemSize.stack.1.1', '-OvQU', 'DELL-NETWORKING-CHASSIS-MIB');
+    $mempool['used']  = $mempool['total'] * (snmp_get($device, 'dellNetCpuUtilMemUsage.stack.1.1', '-OvQU', 'DELL-NETWORKING-CHASSIS-MIB')/ 100);
+    $mempool['free']  = ($mempool['total'] - $mempool['used']);
+} elseif (preg_match('/.6027.1.3.[0-9]+$/', $device['sysObjectID'])) {
     $mempool['total'] = snmp_get($device, 'chSysProcessorMemSize.1', '-OvQU', 'F10-S-SERIES-CHASSIS-MIB');
     $mempool['used']  = $mempool['total'] * (snmp_get($device, 'chStackUnitMemUsageUtil.1', '-OvQU', 'F10-S-SERIES-CHASSIS-MIB')/ 100);
     $mempool['free']  = ($mempool['total'] - $mempool['used']);
```

**Comment by f0o** [comment] 2017-10-25 04:53
Nice!

Yeah the FW upgrade changed all OIDs it seems...

I'd like to test this against a non-stacked f10, we only have stacked S-series sadly.

Memory and Temp will require a loop over the stacks as well.

I will make a proper PR once we know this is the right path.

- f0o

**Comment by laf** [comment] 2017-11-25 21:23
Can we get these patches submitted as pull requests?

**Comment by laf** [comment] 2017-12-09 19:57
Closing, no further info or feedback provided.

**Closed by laf** 2017-12-09 19:57 UTC
Labels: Bug, Help Wanted
