### ISSUE TITLE
Generic method to prevent interface churn of "Transient Ports"

### ISSUE THREAD

**Issue by zatricky** [librenms/librenms#1993] opened 2015-09-25 09:02 UTC
I realise this is already in the [roadmap](http://docs.librenms.org/General/Roadmap/) which includes two port examples: "Eliminate interface churn for transient interfaces (e.g. ppp/tun) on net-snmp."

If the feature is implemented, it would be most helpful if it is generic. I can also imagine there are a few ways it might be fixed which does not appear yet to be documented or discussed publicly. I realise also that this is a tall order. ;)

The way I imagine this might be presented to the admin:
* global regex (perhaps hard-coded default with an option to change)
 * regex per-host override

Additionally an option to choose between:
* ignore the port/s completely
* aggregate the ports
 * all ports into one aggregate port
 * all ports separated into a smaller number of aggregate ports based on another regex
 * all ports separated into a smaller number of aggregate ports based on arp information

I imagine the aggregation might be useful - and "sub-aggregation" even more so. With both ppp/tun and my case with XEN (expanded below), eliminating the port completely would mean the data point is lost. By identifying the port differently, the data can again become meaningful.

##### My scenario
I'm facing this issue is due to XENServer hosts. VM ports require a corresponding "virtual switch interface" on the host. When VMs are migrated between hosts (typically due to host maintenance) or when VMs are decommissioned, the old interfaces remain in the Host's port list within LibreNMS indefinitely. Even though the VMs are technically long-lived and by definition "non-transient", the ports on the hosts behave like transient ports as they are dynamically generated.

Additionally, the number of ports we are seeing in LibreNMS is far more than the number of VMs we've ever had. Thus I believe that migrating a VM from hostA to hostB and back to hostA actually results in 3 such ports within LibreNMS.

The resulting problem is that the interface RRDs are taking up far more diskspace than we anticipated - and the end-result is that we may manually have to delete the old RRDs or permanently remove the XEN Hosts from LibreNMS (until the feature is implemented of course).

The ports on the XEN hosts are as follows:
* permanent (or apparently permanent) ports
 * lo, eth0-eth3
 * xenbr0
 * ovs-system
 * xapi0-xapi5
* "transient" ports
 * vif0.0 - vif793.0
 * tap0.0 - tap793.0

**Comment by f0o** [comment] 2015-09-25 09:05
Duplicate of #386

**Closed by f0o** 2015-09-25 09:05 UTC
Labels: Duplicate

**Comment by laf** [comment] 2015-09-25 10:10
@zatricky If you can add your comments to #386 that would be good.
