### ISSUE TITLE
snmp-scan.php not adding devices with corrected Short hostnames

### ISSUE THREAD

**Issue by jmoore2016** [librenms/librenms#4003] opened 2016-08-08 17:05 UTC
I am using snmp-scan.php to discover/add devices and I have Short hostnames set in my config.php as follows:

`$config['mydomain'] = 'domain.int';`

However, hostnames are not being subtended with the domain name when they are added to LibreNMS device list.

My config.php is as follows:

```
$config['snmp']['community'] = array("mycommunity");
$config['snmp']['timeout'] = 1;
$config['snmp']['retries'] = 2;
$config['snmp']['version'] = "v2c";
$config['snmp']['transports'] = array('udp');

$config['poller-wrapper']['alerter'] = FALSE;

$config['autodiscovery']['nets-exclude'][] = '199.180.176.0/24';
$config['autodiscovery']['nets-exclude'][] = '10.10.75.1/32';
$config['nets'][] = '10.10.75.0/24';
$config['autodiscovery']['nets-exclude'][] = '10.10.0.1/32';
$config['nets'][] = '10.10.0.0/24';
$config['bad_iftype'][]= 'ieee8023adLag';
$config['bad_iftype'][]= 'tunnel';
$config['bad_iftype'][]= 'softwareLoopback';
$config['bad_iftype'][]= 'propPointToPointSerial';
$config['bad_iftype'][]= 'propVirtual';
$config['bad_iftype'][]= 'other';
$config['force_ip_to_sysname'] = true;
$config['addhost_alwayscheckip']   = true;
$config['mydomain'] = 'domain.int';
$config['autodiscovery']['bgp'] = false;
$config['autodiscovery']['ospf'] = false;
$config['autodiscovery']['xdp'] = false;
```

**Comment by f0o** [comment] 2016-08-08 17:08
does addhost.php do that?

**Comment by jmoore2016** [comment] 2016-08-08 17:21
I just tested using "./addhost.php 10.10.75.75" and I can confirm it has the same behavior.

**Comment by murrant** [comment] 2016-08-09 19:31
I'm pretty sure this was intended only for autodiscovery.

We could move the check into the common addHost function so it works with all adds, thoughts?

**Comment by murrant** [comment] 2016-08-09 19:45
Never mind.   Looking at the code, snmp-scan.php adds based on what is resolved by reverse dns, which should always be an fqdn name. 

As for addhost.php and the webui, I think we should respect what the user typed in.

**Comment by jmoore2016** [comment] 2016-08-09 20:51
The whole purpose for needing this functionality is because I am using $config['force_ip_to_sysname'] = true;

So in my case with $config['force_ip_to_sysname'] = true; snmp-scan.php does not use reverse DNS.

**Comment by murrant** [comment] 2016-08-10 09:01
So, what you are telling me is that you are adding everything by IP?

force_ip_to_sysname is a display only thing.  It has no effect on adding devices.

It sounds like you want DNS labeled devices without DNS.  This is not really possible.

**Comment by jmoore2016** [comment] 2016-08-10 15:30
Yes the devices are all being added by IP but shown by sysName. Are you stating that the $config['mydomain'] = 'domain.int'; setting does not apply to how the device is visually shown? If not for visual purposes, then my question is what the practical use case for $config['mydomain'] = 'domain.int'; is supposed to be?

**Comment by murrant** [comment] 2016-08-10 17:09
No, only how they are added.

When you set the syName setting, it just displays exactly what is set in the sysName field.

**Comment by jmoore2016** [comment] 2016-08-10 20:02
So $config['mydomain'] = 'domain.int'; is used only if a DNS lookup returns just a hostname but not a TLD?

**Comment by murrant** [comment] 2016-08-11 12:59
Correct, it also checks that the full name can be resolved before using it.

**Comment by laf** [comment] 2016-08-12 20:17
Closing this.

**Closed by laf** 2016-08-12 20:17 UTC
