### ISSUE TITLE
Feature Request: Force push of hosts to Oxidized

### ISSUE THREAD

**Issue by NerdBlender** [librenms/librenms#5503] opened 2017-01-18 17:43 UTC
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for feature requests or bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Unless your issue is for a WebUI fix or feature then please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Would be a useful addition to have a way of manually forcing a host to have oxidized pull its config, or a global re-push of hosts to oxidized. I sometimes add devices without SNMP checks while they are configured or being tested, but when enable SNMP and discovery / polling happens, LibreNMS won't send the host to oxidized unless its removed and re-added.

Also useful to have this per single host - for quickly getting backup before maintenance

**Comment by murrant** [comment] 2017-01-28 03:32
Duplicate of #3592

**Closed by murrant** 2017-01-28 03:32 UTC
