### ISSUE TITLE
Add support for  Ruckus R600/610/710 gear 

### ISSUE THREAD

**Issue by daniagar** [librenms/librenms#8523] opened 2018-04-08 11:54 UTC
**DO NOT DELETE THIS INFORMATION.**

> **Please read this information carefully.**

**GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z.** 

**You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).**

**If you have a feature request/changes please post this on our [community site](https://community.librenms.org/c/feature-requests).**

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [ ] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [ ] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide **ALL** info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [ ] Please provide as much detail as possible.
- [ ] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

https://p.libren.ms/view/19222021 
https://p.libren.ms/view/0af6ffaa 
https://p.libren.ms/view/3a2086a1 

validate.php:
![image](https://user-images.githubusercontent.com/34174425/38467084-ef084012-3b3b-11e8-95c7-70b1ecd7e9c8.png)

====================================
Component | Version
--------- | -------
LibreNMS  | 1.38-18-ga81e2d2
DB Schema | 247
PHP       | 7.1.13
MySQL     | 5.5.56-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
====================================

[OK]    Composer Version: 1.6.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct

Vendor si correctly recognised but no wifi info is available an all 3 platforms. 

If any other info is needed please specify. 

Thank you.

**Comment by laf** [comment] 2018-04-08 12:12
Assuming duplicate of #8524

Please just edit your issue rather than opening / closing multiple issues.

**Closed by laf** 2018-04-08 12:12 UTC
