### ISSUE TITLE
Eaton UPS shows up as generic

### ISSUE THREAD

**Issue by GarlandM** [librenms/librenms#3508] opened 2016-05-08 17:52 UTC
Eaton 5P 2200 shows up as generic, no info given.

Discovery.php - http://pastebin.com/s1LRY2ME
poller.php - http://pastebin.com/mq2ApYsx

**Comment by oam7575** [comment] 2016-05-09 03:48
@GarlandM 

Possibly a duplicate of my bug : https://github.com/librenms/librenms/issues/3364

Try adjusting /opt/librenms/includes/discovery/os/eatonups.inc.php as per my issue and see if you have any more luck.

After adjusting rerun your discovery and poller tasks as configured in Cron or wait a few mins.

**Comment by GarlandM** [comment] 2016-05-09 07:36
I'll give that a try, but it's a brand new UPS (new production)

**Comment by oam7575** [comment] 2016-05-10 02:01
@GarlandM 

My understanding is that Observium have added support for devices since LibreNMS forked many years ago.

Best bet is to test and feedback for the improvement of LibreNMS

**Comment by oam7575** [comment] 2016-05-28 03:55
I have been hacking away a little and think I have the detection for low end Eaton 5P / 5PX devices working a bit better.

my fork is here : https://github.com/oam7575/librenms

I will be updating my ticket with a pull request and see what happens.

**Comment by Rosiak** [comment] 2016-05-31 20:02
Tagging #3572

**Comment by Rosiak** [comment] 2016-07-29 13:32
Any news?

**Comment by engageant** [comment] 2016-07-29 16:34
Chiming in to say I'm running into this too on my new Eaton 5P.

**Comment by Rosiak** [comment] 2016-08-29 20:36
@oam7575 Any news?

**Closed** 2016-09-09 16:57 UTC
Labels: Needs-Info, New-Device
