### ISSUE TITLE
Cisco IMC Temp + Voltage Readings

### ISSUE THREAD

**Issue by Blorpy** [librenms/librenms#5978] opened 2017-02-22 22:20 UTC
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the ====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | a8691680abb479ba7398d520fff01c1cffe228a0
DB Schema | 165
PHP       | 5.4.16
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.5.6
SNMP      | NET-SNMP 5.7.2
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Having an issue with polling Cisco Integrated Management Console devices. The device is discovered seemingly okay but the temperatures all remain at 0. 
<img width="675" alt="screen shot 2017-02-22 at 2 51 55 pm" src="https://cloud.githubusercontent.com/assets/22355497/23234189/7c383fa8-f90e-11e6-9bd8-b6e3bc9759b5.png">

As does motherboard input voltage:

<img width="653" alt="screen shot 2017-02-22 at 2 54 22 pm" src="https://cloud.githubusercontent.com/assets/22355497/23234303/e175c70a-f90e-11e6-9ad5-ce58ec58599c.png">

I've tested this on firmware 2.2 and 3.0 and both give the same results. LMW what output is helpful from LibreNMS and I'm happy to provide it.

**Comment by geordish** [comment] 2017-02-22 23:00
We need everything in point 3.

**Comment by Blorpy** [comment] 2017-02-22 23:19
https://gist.github.com/Blorpy/0cb5e0a6b5d791ecdd0ceeee722a2f8b

**Comment by laf** [comment] 2017-02-22 23:27
Your device doesn't seem to return data back for the oids we lookup:

No Such Object available on this agent at this OID

Do you have snmp views in place restricting the data returned as you're using snmp v3?

**Comment by Blorpy** [comment] 2017-02-22 23:31
Nothing like that, no. It's not even possible to configure views on these things actually.

**Comment by laf** [comment] 2017-02-22 23:42
Can you see if the missing mibs help (I can't see it would be try anyway):

```
curl ftp://ftp.cisco.com/pub/mibs/ucs-mibs/CISCO-UNIFIED-COMPUTING-MIB.my -o /opt/librenms/mibs/cisco/CISCO-UNIFIED-COMPUTING-MIB
curl ftp://ftp.cisco.com/pub/mibs/ucs-mibs/CISCO-UNIFIED-COMPUTING-TC-MIB.my -o /opt/librenms/mibs/cisco/CISCO-UNIFIED-COMPUTING-TC-MIB
```

**Comment by Blorpy** [comment] 2017-02-23 01:02
No change unfortunately.

**Comment by laf** [comment] 2017-02-23 08:28
I don't have any of these devices to test against but from your output it shows that the OIDs we look up don't respond back.

If you can provide full snmp access to a unit we can do more debugging unless @adaniels21487 can shed any light.

**Comment by Blorpy** [comment] 2017-02-23 16:35
All of these boxes live behind firewalls + NAT that I don't control sadly. Is there any information that I can provide to help fix this problem?

Doing some snmpwalking it looks like the DIMM temp is stored in .1.3.6.1.4.1.9.9.719.1.30.12.1.6.1 through .24 for me. 

I'm curious what version of the CIMC was polled to make the original commit (https://github.com/librenms/librenms/pull/4454/commits/129205a2e5952891094b45f37202484de21bcb66) since as mentioned 2.2 (which is long stable) and 3.0 (new, but now the "gold star") both give me the same results.

**Comment by adaniels21487** [comment] 2017-02-24 00:27
Hi @Blorpy 
The module was build and tested against CIMC versions 1.5(1b) and 1.4(3v).

You mention that you have done some snmpwalks and found your temperature in .1.3.6.1.4.1.9.9.719.1.30.12.1.6.1 and this is where the module checks. See:
https://gist.github.com/Blorpy/0cb5e0a6b5d791ecdd0ceeee722a2f8b#file-gistfile2-txt-L1534-L1556

LibreNMS is getting "No Such Object available on this agent at this OID", if you can get information out of the same OID's, I'd love to see that snmpwalk output.

**Comment by Blorpy** [comment] 2017-02-24 01:19
Hey @adaniels21487 

Okay, that explains it, I'm guessing there were changes from 1.5->2.0+ but I don't get why we're getting "No Such Object available on this agent at this OID" when clearly snmpwalk shows there are values. 

Here is the SNMP walk for what appears to be the DIMM related info https://gist.github.com/Blorpy/f4937e53197b73eab9fb96f9f3a363db

**Comment by laf** [comment] 2017-02-24 09:59
So it's `.1.3.6.1.4.1.9.9.719.1.9.44.1.41` that's causing the problem. I actually can't see in the code where this comes from.

Can you get the output from in mysql:

`select * from sensors where sensor_oid='.1.3.6.1.4.1.9.9.719.1.9.44.1.41';`

**Comment by adaniels21487** [comment] 2017-02-24 12:00
Truly bazaar.
Can you try running the command LibreNMS does from your command line:
https://gist.github.com/Blorpy/0cb5e0a6b5d791ecdd0ceeee722a2f8b#file-gistfile2-txt-L1534

**Comment by Blorpy** [comment] 2017-02-24 16:06
As requested: https://gist.github.com/Blorpy/3f2963d57890c3fad255d58557d68d9d

The snmpget returns values... So I have no idea whats going on here.

**Comment by wriedel** [comment] 2017-02-26 06:43
@laf I have the same issue over here with CIMC on C240 and C420
http://pastebin.com/ZGM1Nb1F
http://pastebin.com/uFJKWRSh
First I thought something is wrong with my eyes but sometimes the data, even long term, shows up and sometimes it does not. So I guess it's more a GUI or timeout thing.
Also it may be that we hit an OID of death as I see a lot of "app_monitor.c:542:Restarting Process snmp-subagentd" on the CIMC

**Comment by wriedel** [comment] 2017-02-26 06:50
maybe related to a change around the 8th of February as a lot of values dropped down to ZERO at the time

**Comment by adaniels21487** [comment] 2017-02-26 21:45
Feb 8, Possibly #5778?
From the comments, it appears this may have caused one or two issues with sensors.

**Comment by laf** [comment] 2017-02-26 23:03
I'm not sure how in this case, the OIDs being looked up are all in the discovery code but show no response on a poll. You can see in this output: https://gist.github.com/Blorpy/0cb5e0a6b5d791ecdd0ceeee722a2f8b - search for .1.3.6.1.4.1.9.9.719.1.9.44.1

**Comment by Blorpy** [comment] 2017-02-28 16:54
No idea how that would be happening... I've tried adding a couple more boxes to see if maybe just the two I tried were broken, but I get the same result as above.

**Comment by Blorpy** [comment] 2017-03-01 23:11
Did a git pull to pick up this change, rediscovered the CIMCs, then ran a poll, but the same (?) issue persists of having 0c for all DIMM temps. 

Error in polling log shows "No Such Object available on this agent at this OID"

**Comment by adaniels21487** [comment] 2017-03-02 21:10
I can't reproduce this on my lab 1.5(b).
If someone can unicast me (aaron@daniels.id.au) the below details I can try with their data:

select * from sensors where device_id=X;
An SNMPwalk of the following branches:
.1.3.6.1.4.1.9.9.719.1.9.44.1
.1.3.6.1.4.1.9.9.719.1.30.12.1
.1.3.6.1.4.1.9.9.719.1.41

Thanks,
Aaron

**Comment by wriedel** [comment] 2017-03-03 09:18
@adaniels21487 as I already mentioned before, at least at my setup, if I see the values I get the full history if not then there is also no history at all. To me it looks like that we continue to poll, collect and write into the database without any issue but we just visualize based on unknown conditions.
If I look at my list of "Polling Duration" the CIMC are not on top of this list with 5-6 sec after disabling unneeded stuff so it shouldn't be a timeout thing on the collection side. 
So what is needed to drill down on this?

**Comment by laf** [comment] 2017-03-03 09:33
@wriedel The output of the walks he's asked for above + the output of the select in mysql :)

**Comment by adaniels21487** [comment] 2017-03-03 10:01
Just an update...
@Blorpy has provided details, I am working with him on this.

@wriedel 
your pastebins (above) have expired, if you can send me a verbose poller debug (./poller.php -v -h X -m sensors), I can see if you are hitting the same issue. Feel free to sanitise the community string.

Aaron

**Comment by wriedel** [comment] 2017-03-03 10:37
@adaniels21487 I have send the over via PM.
Many thanks!

**Comment by adaniels21487** [comment] 2017-03-05 21:23
Hi @wriedel @blorpy,
Thanks for the info. I have taken a look over both of your poller debugs and see an SNMP error on both:
```
Error in packet
Reason: (genError) A general failure occured
Failed object: XXX
```
The object is different, but the error is the same.
This is followed by the "No Such Object available on this agent at this OID" messages.

I have two theories:
1. You are hitting a bug in NET-SNMP.
I am running version 6.0.1-2 from Debian Jessie. I see you are both running 5.7.2, perhaps see if an upgrade solves the issue?

2. You are hitting a bug in the CIMC SNMP stack.
I have extracted all the SNMP calls from both of your debugs and emailed them back. Can you try running all these at once to see if this issue is caused by overloading the CIMC with requests?
If you see the error, perhaps retry, backing off just before the error and see if you can manually throttle queries to get it to successfully return data.

Googling for this error seems to suggest that it is theory 2.

Please let me know what you find.

**Comment by Blorpy** [comment] 2017-03-05 21:47
Is that net-snmp 6.0.1-2 package Debian maintained then? The latest I see from the project itself is 5.7.3. 

Running all the SNMP gets at once occasionally results in the error you list above, but 90% of the time I just get "No Such Object available on this agent at this OID". Running these gets individually does return results about 50% of the time... The other times I still get "No Such Object available on this agent at this OID" for random gets. Shall play with this more and see if theres any pattern to it.

**Comment by adaniels21487** [comment] 2017-03-06 05:35
Ok, I am seeing this on some of my devices.
This looks like a CIMC bug.

I performed 2 snmpget's while doing a packet capture, one capture did not work and the next did.

Failed:
![image](https://cloud.githubusercontent.com/assets/13431617/23597851/31a8f8f6-0282-11e7-85b4-8a0ce61729af.png)

Working:
![image](https://cloud.githubusercontent.com/assets/13431617/23597877/499f914a-0282-11e7-958c-f732a3340eae.png)

As this is at the protocol layer, I can't blame net-snmp.

**Comment by laf** [comment] 2017-03-06 14:09
I'm closing this issue as it seem unrelated to LibreNMS itself. Please continue this discussion on the community site: https://community.librenms.org/t/cisco-imc-temp-voltage-readings/769

**Closed by laf** 2017-03-06 14:09 UTC
Labels: Needs-Info

**Comment by wriedel** [comment] 2017-03-06 17:28
Hi @adaniels21487 I am pretty sure that's not related to net-snmp as I have two identical servers and one is working fine while the other is not. So I agree with possibility 2 which is CIMC related and looks to be similar to this: https://supportforums.cisco.com/discussion/11950421/c220m3-cimc-snmp-implementation.
Let me open a SR with CISCO TAC to drill down in this one.
Many thanks,
Wolfgang

**Comment by wriedel** [comment] 2017-03-08 12:34
Hi @adaniels21487 and @laf, I think we're facing two separate issue here.
1. Is related to a CIMC issue and there is not much we can do about
2. While having the graphs I still see 0 in the main page. Please have a look at the attached screen shots.
![screen shot 2017-03-08 at 13 30 34pm](https://cloud.githubusercontent.com/assets/2451855/23704161/d9656566-0403-11e7-8676-d0ed9f16ce41.jpg)
![screen shot 2017-03-08 at 13 30 10pm](https://cloud.githubusercontent.com/assets/2451855/23704162/d967c964-0403-11e7-8359-4f19a123abda.jpg)

**Comment by laf** [comment] 2017-03-08 14:39
Isn't your debug output showing that when the cimc sends back the bad response you don't get any further data and thus the results being zero for existing sensors?

**Comment by wriedel** [comment] 2017-03-09 01:15
@laf not really,
I see this on the main page:
![screen shot 2017-03-09 at 02 13 05am](https://cloud.githubusercontent.com/assets/2451855/23731448/0b4f7746-046e-11e7-830e-84b842f124c6.jpg)

and this within the detail page this, which is definitly !EQ 0
![screen shot 2017-03-09 at 02 13 19am](https://cloud.githubusercontent.com/assets/2451855/23731484/311c0c50-046e-11e7-8eb2-2ca196711d0b.jpg)
