### ISSUE TITLE
Cannot re-add previously removed device

### ISSUE THREAD

**Issue by Ftelf** [librenms/librenms#1321] opened 2015-06-22 07:49 UTC
My libreNMS-dev is run on vmware image from librenms.org.
I have deleted one router device:
http://fii.cz/jfxbvj
Seems like there is permission problems for the web-server. rrds have different permissions.

Now I added the device again:
http://fii.cz/vveyw

I have deleted the rrd/10.154.121.1 directory manually as root.
The same:
http://fii.cz/vveyw

Seems like there still sit some info about this device, preventing adding it again.
I cannot see this device in any list though.

**Comment by f0o** [comment] 2015-06-22 09:06
Related if not even being the cause: #1322

**Comment by laf** [comment] 2015-06-22 10:28
Yeah, helped on irc sort this and created the issue. Closing.

**Closed by laf** 2015-06-22 10:28 UTC
