### ISSUE TITLE
Powerwalker UPS data incorrect

### ISSUE THREAD

**Issue by tslytsly** [librenms/librenms#6933] opened 2017-07-03 09:47 UTC
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for  bugs, please do not post issues asking for help or how to do X, Y or Z. 
You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).
If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

```
==========================================================
Component | Version
--------- | -------
LibreNMS  | 701fbbc29b7a25e215032a6435fac72c06094976
DB Schema | 198
PHP       | 7.0.18-0ubuntu0.16.04.1
MySQL     | 10.0.29-MariaDB-0ubuntu0.16.04.1
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
==========================================================
```
Pastebin links: 
Disco: https://p.libren.ms/view/4d50fdc1
Poll: https://p.libren.ms/view/99adf121
SNMPWalk: https://p.libren.ms/view/b6907a29

**Details**
LibreNMS seems to report battery voltage and frequency slightly wrong for Powerwalker UPS.

Ours is showing Batt volts of 205.2v and Output Freq as 50.0Hz on its inbuilt webpage, but in LNMS it's showing as 2052v and 500Hz.

This seems to be because it reports the data without decimal places. 
Input and Output voltage get reported correctly, so it's showing Output voltage of 230.0 on LNMS, even though the MIB reports 2300.

**Comment by laf** [comment] 2017-07-03 19:12
What version of software are you running on these? Data from another powerwalker shows it's fine so we need to work out of if this is a difference on the software version.

**Comment by tslytsly** [comment] 2017-07-03 19:54
Web manager reports firmware is 1.4.0.3

**Comment by laf** [comment] 2017-07-03 20:27
Ok, so we have a problem here. The divisor for all of these voltages should be set as 10 which would fix the upsBatteryVoltage one but break the two others. 

I'm going to move the powerwalker devices to use rfc compat code which will mean you will lose existing graphs I'm afraid, but it standardises the code and also includes some additional metrics not currently available. It won't actually fix the overall issue for you though and you will find two voltage values still reporting wrong. You will need to raise this with your vendor to fix.

**Comment by tslytsly** [comment] 2017-07-03 21:02
Ok, just so I understand this a bit better... Is this the way the ups is reporting its voltage? For example, should it be telling us what to devide the values by? Or is that coded into lnms? 
Why does it get some of them right but others wrong? 
This is so I can explain to the vendor what needs changing.

**Comment by laf** [comment] 2017-07-03 21:04
So this device uses the standard UPS-MIB (which is great), the problem is that values returned from this by default should require you to divide them by 10 to get the actual human readable value (i.e it's 0.1 of a volt). The problem with this for your device is that the vendor is sending some data as 1 volt, some as 0.1 volt which means we don't know what do divide by. Make sense?

**Comment by tslytsly** [comment] 2017-07-04 07:41
Ah I get you. 
I've just been playing with a mib browser, and I can see what you are saying. Using the standard MIBs it does seem to report some voltages and the frequency with the requirement to divide by 10 and not others.

However, if you use the MIBs provided for this UPS network card (http://powerwalker.com/software/NMC/NMC_MIB.zip) it reports all voltages and frequencies the same way. Can we not use these MIBs instead?

**Comment by laf** [comment] 2017-07-04 09:43
Which of the two mibs are you referring to and do you have some example OIDs to check?

**Comment by tslytsly** [comment] 2017-07-04 12:57
The ones provided by Powerwalker on their [website.](http://powerwalker.com/software/NMC/NMC_MIB.zip)
Specifically: 
**Input Voltage**:
OID: .1.3.6.1.4.1.935.10.1.1.2.16.1.3.1
**Input Freq**:
OID: .1.3.6.1.4.1.935.10.1.1.2.16.1.2.1

**Ouput Voltage**:
OID: .1.3.6.1.4.1.935.10.1.1.2.18.1.3.1
**Output Freq**:
OID: .1.3.6.1.4.1.935.10.1.1.2.18.1.2.1

**UPS Batt Volts**:
OID: .1.3.6.1.4.1.935.10.1.1.3.5.0

**Comment by laf** [comment] 2017-07-14 21:36
This will be merged on the 20th of July

**Comment by tslytsly** [comment] 2017-07-16 20:01
thanks @laf 
Great community around LibreNMS. 
👍

**Closed** 2017-07-20 11:01 UTC
Labels: Blocker, New-Device
