### ISSUE TITLE
Caching Mac OUI data 'FAIL'

### ISSUE THREAD

**Issue by nanedi** [librenms/librenms#15180] opened 2023-08-01 19:06 UTC
### The problem

```
:~$ ./daily.sh
/opt/librenms/.env: line 6: F.DyTSf+7Z^m: command not found
Updating to latest codebase                        OK
/opt/librenms/.env: line 6: F.DyTSf+7Z^m: command not found
Updating Composer packages                         OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK
Caching Mac OUI data                               FAIL
/opt/librenms/.env: line 6: F.DyTSf+7Z^m: command not found
Not able to acquire lock, skipping mac database update
```

### Output of ./validate.php

```txt
:~$ ./validate.php
===========================================
Component | Version
--------- | -------
LibreNMS  | 23.7.0-38-g726563185 (2023-08-01T03:22:09-07:00)
DB Schema | 2023_06_02_230406_create_vendor_oui_table (253)
PHP       | 8.1.2-1ubuntu2.13
Python    | 3.10.12
Database  | MariaDB 10.6.12-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.5.8
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

Previous version.

**Comment by electrocret** [comment] 2023-08-02 02:27
Addressed by https://github.com/librenms/librenms/pull/15175

**Closed** 2023-08-02 13:30 UTC

**Comment by nanedi** [comment] 2023-08-02 16:09
@murrant murrant
Problem:
```
Caching Mac OUI data                               FAIL
Not able to acquire lock, skipping mac database update
```

```
:~$ ./daily.sh
Updating to latest codebase                        OK
Updating Composer packages                         OK
Updated from 726563185 to 91c57a1ee                OK
Updating SQL-Schema                                OK
Updating submodules                                OK
Cleaning up DB                                     OK
Fetching notifications                             OK
Caching PeeringDB data                             OK
Caching Mac OUI data                               FAIL
Not able to acquire lock, skipping mac database update
```

**Comment by murrant** [comment] 2023-08-02 22:10
This is actually a bad return code.  Skipping due to the lock not being expired should not be a failure.

**Comment by nanedi** [comment] 2023-08-02 22:13
@murrant
Do you have any idea to fix it?

**Comment by murrant** [comment] 2023-08-02 22:14
Yes, ignore it for now until a fix is merged upstream.
Literally no issues caused by this failure.

**Comment by nanedi** [comment] 2023-08-02 22:15
Thanks
