### ISSUE TITLE
Read 64-bit counters where available from Cisco SG300 switches

### ISSUE THREAD

**Issue by itvirta** [librenms/librenms#7756] opened 2017-11-17 09:45 UTC
LibreNMS reads only 32-bit counters on (some) Cisco SG300 series small business switches, since [they have `bad_ifXEntry` set](https://github.com/librenms/librenms/blob/master/includes/definitions/ciscosb.yaml#L10). This predictably causes issues with 1 Gb/s links, since an average of only 115 Mb/s over 5 minutes is enough to overflow the counter. 

The `bad_ifXEntry` flags were set in this commit: https://github.com/librenms/librenms/pull/4502

Removing them fixes the per-byte graphing, but breaks the unicast packet graphs, since the switch doesn't seem to give useful values in `ifHCInUcastPkts`, only zeroes. However, the data in `ifInUcastPkts` seems fine, and the smaller counter should not be a problem in this case since packet counters are harder to overflow. (It's also what is currently used, with `bad_ifXEntry` set.)

The code in `includes/polling/ports.inc.php` [checks the HC counters individually](https://github.com/librenms/librenms/blob/master/includes/polling/ports.inc.php#L484), but since it also 
[optimizes the polling](https://github.com/librenms/librenms/blob/master/includes/polling/ports.inc.php#L217) and does not load the 32-bit counters if `ifXEntry` was loaded, `ifInUcastPkts` is not available to fall back to.

To fix the issue, I suggest adding a check for nonzero `ifHCInUcastPkts` among the other related sanity checks that already are there, so that the code falls back to loading `ifEntry` in full if `ifHCInUcastPkts` doesn't have a sane value. Doing that, and removing `bad_ifXEntry` seems to fix both the byte and packet graphs for me.

Another possible solution would be to create a per-model flag to tell the program to load both `ifXEntry` and `ifEntry` on these devices. Like `bad_ifXEntry` but not as harsh. 

I tested this on an SG300-10SFP. One can only assume that the other models in the series are similar. 

------------------------------------------------------

Version info:

```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-114-g22f4974
DB Schema | 215
PHP       | 5.6.30-0+deb8u1
MySQL     | 10.0.32-MariaDB-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
====================================
```

------------------------------------------------------

DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our [Discord server](https://t.libren.ms/discord) to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
- [ ] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).

That seems to be about adding a new OS

- [x] Please provide as much detail as possible.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.

**Comment by laf** [comment] 2017-11-17 09:48
Please submit your proposed fixes as a PR.

Alternatively turn on selected port polling.

**Comment by itvirta** [comment] 2017-11-17 14:05
@laf here: https://github.com/librenms/librenms/pull/7758

I did wonder about the fact that selected port polling doesn't seem to use `bad_ifXEntry`. This seems odd. If the data for some device is known to be bad, shouldn't it be bad regardless of what method is used to poll it?

**Comment by mattorola7** [comment] 2018-01-02 15:23
I am having trouble with my Cisco 4948 graphing traffic > 115Mbps. I've read this thread and I can't find anywhere in the documentation that is relevant to enabling "selective polling" for switch ports.

**Comment by murrant** [comment] 2018-01-09 15:31
@itvirta the problem is not the data, it is the time.  Walking full tables takes a long time so we need to optimize and only walk what is needed.  If we had 100% data collect we could easily detect bad data, but it would take way more than 5 minutes to poll some devices.  Per-port polling works differently so it has different optimizations.

@mattorola7 https://docs.librenms.org/Support/Performance/#per-port-polling-experimental

**Comment by laf** [comment] 2018-02-10 22:19
Closing this down as the PR was also closed and no other discussions have happened.

**Closed by laf** 2018-02-10 22:19 UTC
