### ISSUE TITLE
IPv6 addresses in bgpPeerIdentifier should be compressed

### ISSUE THREAD

**Issue by Absynth723** [librenms/librenms#13659] opened 2022-01-10 09:52 UTC
### The problem

The bgpPeerIdentifier for IPv6 BGP peers is displayed in uncompressed notation (for example in alerts). As per the recommendation in RFC5952, it should be displayed in compressed notation. 

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.12.1-11-g6dc3e4217
DB Schema | 2021_11_29_165436_improve_ports_search_index (229)
PHP       | 7.4.16
Python    | 3.8.10
MySQL     | 10.3.32-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.2.3
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[FAIL]  Database: missing column (ports_perms/id)
[FAIL]  Database: incorrect column (ports_perms/user_id)
[FAIL]  Database: incorrect column (ports_perms/port_id)
[FAIL]  We have detected that your database schema may be wrong
	[FIX]:
	Run the following SQL statements to fix it
	SQL Statements:
	 ALTER TABLE `ports_perms` ADD `id` bigint unsigned NOT NULL auto_increment PRIMARY KEY FIRST;
	 ALTER TABLE `ports_perms` CHANGE `user_id` `user_id` int unsigned NOT NULL ;
	 ALTER TABLE `ports_perms` CHANGE `port_id` `port_id` int unsigned NOT NULL ;
```

### Anything in the logs that might be useful for us?

```txt
n/a
```

**Comment by murrant** [comment] 2022-03-11 17:28
It is shown compressed in the web ui in all places I can find it.  Please include a screenshot.

If you want it compressed in your alert template you will need to compress it. Something like this:
`{{ \LibreNMS\Util\IP::parse($value['bgpPeerIdentifier'], true)->compressed() }}`

**Comment by PipoCanaja** [comment] 2023-11-13 18:12
No details provided and can't reproduce the issue. Closing

**Closed by PipoCanaja** 2023-11-13 18:12 UTC
Labels: User-Pending
