### ISSUE TITLE
Huawei NE40E - BGP peers appearing multiple times

### ISSUE THREAD

**Issue by kamils85** [librenms/librenms#14357] opened 2022-09-16 09:02 UTC
### The problem

Hello,

BGP Routing table is showing each EBGP peer 90 times. I have 13 peers and LibreNMS shows 1170. No idea since when the issue started but I've noticed about 2 weeks ago.

![image](https://user-images.githubusercontent.com/23239006/190587247-39526355-a902-4bf4-bbff-4bb6b4c72e4b.png)

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 22.8.0-91-g7aeb238b7
DB Schema | 2022_09_03_091314_update_ports_adsl_table_with_defaults (246)
PHP       | 8.1.9
Python    | 3.8.10
Database  | MariaDB 10.5.13-MariaDB-1:10.5.13+maria~focal
RRDTool   | 1.7.2
SNMP      | 5.8
====================================

[OK]    Composer Version: 2.4.1
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    
[OK]    Database schema correct
[OK]    MySQl and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

22.8.0

### Device info

Huawei NE40E

### Discovery output

```txt
will upload as separate file due to file length.
```

### Poller output

```txt
will upload as separate file due to file length.
```

**Comment by kamils85** [comment] 2022-09-16 09:03
[discover-10.8.8.2.txt](https://github.com/librenms/librenms/files/9582503/discover-10.8.8.2.txt)
[poller-10.8.8.2.txt](https://github.com/librenms/librenms/files/9582504/poller-10.8.8.2.txt)

**Comment by PipoCanaja** [comment] 2022-09-18 09:55
Hi @kamils85 Fix is on the way but I have some difficulties with the automated tests.

**Comment by PipoCanaja** [comment] 2022-09-18 12:27
@kamils85 Looks like it is ready for review and hopefully merge soon. In the meantime, we'd be happy if you can test the PR and confirm it fixes your issue.

**Comment by kamils85** [comment] 2022-09-19 06:54
@PipoCanaja I've applied the patches, did the rediscovery and I run the poller again but I don't see any difference. Is there anything else I should run? 

```
librenms@nms1:~$ ./scripts/github-apply 14278
Checking patch LibreNMS/Modules/LegacyModule.php...
Checking patch app/Models/BgpPeer.php...
Checking patch includes/discovery/bgp-peers/dell-os10.inc.php...
Checking patch includes/discovery/bgp-peers/firebrick.inc.php...
Checking patch includes/discovery/bgp-peers/vrp.inc.php...
Checking patch tests/data/asa.json...
Checking patch tests/data/firebrick_2900.json...
Checking patch tests/data/firebrick_6000.json...
Checking patch tests/module_tables.yaml...
Applied patch LibreNMS/Modules/LegacyModule.php cleanly.
Applied patch app/Models/BgpPeer.php cleanly.
Applied patch includes/discovery/bgp-peers/dell-os10.inc.php cleanly.
Applied patch includes/discovery/bgp-peers/firebrick.inc.php cleanly.
Applied patch includes/discovery/bgp-peers/vrp.inc.php cleanly.
Applied patch tests/data/asa.json cleanly.
Applied patch tests/data/firebrick_2900.json cleanly.
Applied patch tests/data/firebrick_6000.json cleanly.
Applied patch tests/module_tables.yaml cleanly.
```

**Comment by PipoCanaja** [comment] 2022-09-19 08:00
Hum, during discovery, you should not see this error anymore : 
```
SQLSTATE[HY093]: Invalid parameter number (SQL: SELECT COUNT(*) from `bgpPeers` WHERE device_id = 289 AND bgpPeerIdentifier = 88.220.106.137  AND `vrf_id` IS NULL ) (SQL: SELECT COUNT(*) from `bgpPeers` WHERE device_id = 289 AND bgpPeerIdentifier = 88.220.106.137  AND `vrf_id` IS NULL )#0 /opt/librenms/includes/discovery/bgp-peers/vrp.inc.php(91): dbFetchCell()
#1 /opt/librenms/includes/discovery/bgp-peers.inc.php(12): include('...')
#2 /opt/librenms/includes/discovery/functions.inc.php(153): include('...')
#3 /opt/librenms/discovery.php(118): discover_device()
#4 {main}  
```

And you should not see BGP peers increasing.

The BGP Peer deletion code should be redone, but I'll do another PR for it I suppose.

**Comment by kamils85** [comment] 2022-09-19 08:13
Unfortunately I still see these errors:

```
hwBgpPeerSessionExtDescription = No Such Object available on this agent at this OID  
  
Invalid snmp_walk() data = hwBgpPeerSessionExtDescription = No Such Object available on this agent at this OID  

SQL[select exists(select * from `bgpPeers` where `bgpPeers`.`device_id` = ? and `bgpPeers`.`device_id` is not null and `bgpPeerIdentifier` = ? and `vrf_id` is null) as `exists` [289,"88.220.104.141"] 1.27ms] 
  

SQLSTATE[HY093]: Invalid parameter number (SQL: UPDATE `bgpPeers` set `bgpPeerDescr`=?,`bgpPeerRemoteAs`=20804,`astext`=ASN-TELENERGO ul. PERKUNA 47, WARSZAWA, PL WHERE device_id = 289 AND bgpPeerIdentifier = 88.220.104.141  AND `vrf_id` IS NULL ) (SQL: UPDATE `bgpPeers` set `bgpPeerDescr`=?,`bgpPeerRemoteAs`=20804,`astext`=ASN-TELENERGO ul. PERKUNA 47, WARSZAWA, PL WHERE device_id = 289 AND bgpPeerIdentifier = 88.220.104.141  AND `vrf_id` IS NULL )#0 /opt/librenms/includes/discovery/bgp-peers/vrp.inc.php(124): dbUpdate()
#1 /opt/librenms/includes/discovery/bgp-peers.inc.php(12): include('...')
#2 /opt/librenms/includes/discovery/functions.inc.php(153): include('...')
#3 /opt/librenms/discovery.php(118): discover_device()
#4 {main}  

.
SQL[SELECT COUNT(*) from `bgpPeers_cbgp` WHERE device_id = ? AND bgpPeerIdentifier = ? AND afi=? AND safi=? [289,"88.220.104.141","ipv4","unicast"] 1ms] 
  

SQL[select exists(select * from `bgpPeers` where `bgpPeers`.`device_id` = ? and `bgpPeers`.`device_id` is not null and `bgpPeerIdentifier` = ? and `vrf_id` is null) as `exists` [289,"88.220.106.137"] 1ms] 
  

SQLSTATE[HY093]: Invalid parameter number (SQL: UPDATE `bgpPeers` set `bgpPeerDescr`=?,`bgpPeerRemoteAs`=20804,`astext`=ASN-TELENERGO ul. PERKUNA 47, WARSZAWA, PL WHERE device_id = 289 AND bgpPeerIdentifier = 88.220.106.137  AND `vrf_id` IS NULL ) (SQL: UPDATE `bgpPeers` set `bgpPeerDescr`=?,`bgpPeerRemoteAs`=20804,`astext`=ASN-TELENERGO ul. PERKUNA 47, WARSZAWA, PL WHERE device_id = 289 AND bgpPeerIdentifier = 88.220.106.137  AND `vrf_id` IS NULL )#0 /opt/librenms/includes/discovery/bgp-peers/vrp.inc.php(124): dbUpdate()
#1 /opt/librenms/includes/discovery/bgp-peers.inc.php(12): include('...')
#2 /opt/librenms/includes/discovery/functions.inc.php(153): include('...')
#3 /opt/librenms/discovery.php(118): discover_device()
#4 {main}  

.
SQL[SELECT COUNT(*) from `bgpPeers_cbgp` WHERE device_id = ? AND bgpPeerIdentifier = ? AND afi=? AND safi=? [289,"88.220.106.137","ipv4","unicast"] 0.71ms] 
  

SQL[select exists(select * from `bgpPeers` where `bgpPeers`.`device_id` = ? and `bgpPeers`.`device_id` is not null and `bgpPeerIdentifier` = ? and `vrf_id` is null) as `exists` [289,"89.42.162.96"] 0.76ms] 
  

SQLSTATE[HY093]: Invalid parameter number (SQL: UPDATE `bgpPeers` set `bgpPeerDescr`=?,`bgpPeerRemoteAs`=201054,`astext`=EPIX-POLMIX, PL WHERE device_id = 289 AND bgpPeerIdentifier = 89.42.162.96  AND `vrf_id` IS NULL ) (SQL: UPDATE `bgpPeers` set `bgpPeerDescr`=?,`bgpPeerRemoteAs`=201054,`astext`=EPIX-POLMIX, PL WHERE device_id = 289 AND bgpPeerIdentifier = 89.42.162.96  AND `vrf_id` IS NULL )#0 /opt/librenms/includes/discovery/bgp-peers/vrp.inc.php(124): dbUpdate()
#1 /opt/librenms/includes/discovery/bgp-peers.inc.php(12): include('...')
#2 /opt/librenms/includes/discovery/functions.inc.php(153): include('...')
#3 /opt/librenms/discovery.php(118): discover_device()
#4 {main}  

.
SQL[SELECT COUNT(*) from `bgpPeers_cbgp` WHERE device_id = ? AND bgpPeerIdentifier = ? AND afi=? AND safi=? [289,"89.42.162.96","ipv4","unicast"] 0.72ms]
```

**Comment by PipoCanaja** [comment] 2022-09-19 18:57
Ok. I'll try to reproduce the issue and come with a new PR for this one. But first I need #14278 to be merged so it won't be done with this release for sure.

**Comment by kamils85** [comment] 2022-09-20 06:23
Thanks @PipoCanaja for looking at this. Let me know if you need me to test or provide anything else.

**Comment by SantiagoSilvaZ** [comment] 2022-09-29 20:55
@PipoCanaja, I applied this patch and BGP peers stopped increasing, how do I remove duplicate BGP peers?

**Comment by PipoCanaja** [comment] 2022-10-06 18:27
> @PipoCanaja, I applied this patch and BGP peers stopped increasing, how do I remove duplicate BGP peers?

Currently, you can do some mysql magic to delete the peers. The cleaning code has to be fixed.

**Comment by PipoCanaja** [comment] 2022-10-07 20:44
Hi @kamils85  AND @SantiagoSilvaZ 
PR is out : #14431 
Please test it and report if you see any issue. I don't see in my environnement (but have only AR Routers, CloudEngine and Campus switches, no NE). 
Thanx for feedback

**Comment by SantiagoSilvaZ** [comment] 2022-10-09 01:21
Hi,
@PipoCanaja, I don't have NE, I only have CloudEngine.

**Comment by PipoCanaja** [comment] 2022-10-09 09:42
> Hi, @PipoCanaja, I don't have NE, I only have CloudEngine.

As you had the duplication issue, if it is now fixed with the PR, this is enough to make my Sunday :)

**Comment by kamils85** [comment] 2022-10-10 06:54
@PipoCanaja ,
Back in business. Seems to be working fine now.  The duplicate peers are gone.

**Closed** 2022-10-11 18:26 UTC
