### ISSUE TITLE
rrdcached failed with status -1

### ISSUE THREAD

**Issue by wiad** [librenms/librenms#3536] opened 2016-05-19 07:56 UTC
After commits 761f55b I get rrdcached errors for the 'netstats-snmp' rrd on our ASA boxes:

`rrdcached[56392]: queue_thread_main: rrd_update_r (/san1/librenms/rrd/asa5585x-vlan15-pri/netstats-snmp.rrd) failed with status -1. (/san1/librenms/rrd/asa5585x-vlan15-pri/netstats-snmp.rrd: found extra data on update argument: 0)`

It works for all our other boxes, mainly Cisco IOS/nxos, its just the ASA thats not working.

If I revert the commit it works as expected again and the netstats-snmp graphs are populated.

**Comment by paulgear** [comment] 2016-05-22 03:45
I'm seeing the same on my system.

**Comment by paulgear** [comment] 2016-05-22 03:59
I think this is a bug in the referenced commit, and we should revert it; the issue is that there are sometimes non-numeric data returned - i.e. the loop to find numeric info is necessary.  Here's a sample from one of my devices where I've added a d_print_r just after the assignment of $fields:
```
Array
(
    [snmpInPkts] => 4499645
    [snmpOutPkts] => 4499644
    [snmpInBadVersions] => 0
    [snmpInBadCommunityNames] => 0
    [snmpInBadCommunityUses] => 0
    [snmpInASNParseErrs] => 0
    [snmpInTooBigs] => 0
    [snmpInNoSuchNames] => 0
    [snmpInBadValues] => 0
    [snmpInReadOnlys] => 0
    [snmpInGenErrs] => 0
    [snmpInTotalReqVars] => 36412630
    [snmpInTotalSetVars] => 0
    [snmpInGetRequests] => 1142208
    [snmpInGetNexts] => 543
    [snmpInSetRequests] => 0
    [snmpInGetResponses] => 0
    [snmpInTraps] => 0
    [snmpOutTooBigs] => 0
    [snmpOutNoSuchNames] => 0
    [snmpOutBadValues] => 0
    [snmpOutGenErrs] => 0
    [snmpOutGetRequests] => 0
    [snmpOutGetNexts] => 0
    [snmpOutSetRequests] => 0
    [snmpOutGetResponses] => 4499646
    [snmpOutTraps] => 0
    [snmpEnableAuthenTraps] => disabled
    [snmpSilentDrops] => 0
    [snmpProxyDrops] => 0
)
```

**Comment by paulgear** [comment] 2016-05-22 04:02
Also, I think this is resulting in the polled metrics being ignored - it looks like my system stopped graphing netstats-snmp entirely a few weeks ago.
![graph php](https://cloud.githubusercontent.com/assets/107222/15452115/cd6e8304-2025-11e6-8eaa-77d65d030402.png)

Any thoughts, @librenms/reviewers, @geordish ?

**Comment by laf** [comment] 2016-05-22 09:23
Revert it if you need to

**Comment by laf** [comment] 2016-05-22 15:01
Actually, please don't revert that PR otherwise you will break everything again for Influx. I'd suggest just submitting a PR to revert the specific commit.

**Comment by geordish** [comment] 2016-05-22 20:15
So the code to loop through and set the non-numeric to nulls was removed, as it is a duplicate of what is in the rrd_update function. The non numeric values are still getting set to null.

(https://github.com/librenms/librenms/blob/bcafac560c2a1a45ddb5e227d45e6dc4644a1a88/includes/rrdtool.inc.php from line 238)

I have verified this is the same locally:

```
SNMP/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -OQUs  -m SNMPv2-MIB -M /opt/librenms/mibs udp6:HOSTNAME:161 snmpsnmpInPkts.0 = 326800
snmpOutPkts.0 = 326800
snmpInBadVersions.0 = 0
snmpInBadCommunityNames.0 = 0
snmpInBadCommunityUses.0 = 0
snmpInASNParseErrs.0 = 0
snmpInTooBigs.0 = 0
snmpInNoSuchNames.0 = 0
snmpInBadValues.0 = 0
snmpInReadOnlys.0 = 0
snmpInGenErrs.0 = 0
snmpInTotalReqVars.0 = 2700783
snmpInTotalSetVars.0 = 0
snmpInGetRequests.0 = 74489
snmpInGetNexts.0 = 33
snmpInSetRequests.0 = 0
snmpInGetResponses.0 = 0
snmpInTraps.0 = 0
snmpOutTooBigs.0 = 0
snmpOutNoSuchNames.0 = 0
snmpOutBadValues.0 = 0
snmpOutGenErrs.0 = 0
snmpOutGetRequests.0 = 0
snmpOutGetNexts.0 = 0
snmpOutSetRequests.0 = 0
snmpOutGetResponses.0 = 326801
snmpOutTraps.0 = 1
snmpEnableAuthenTraps.0 = disabled
snmpSilentDrops.0 = 0
snmpProxyDrops.0 = 0

[RRD Disabled]RRD[update /opt/librenms/rrd/xxx/netstats-snmp.rrd N:326800:326800:0:0:0:0:0:0:0:0:0:2700783:0:74489:33:0:0:0:0:0:0:0:0:0:0:326801:1:U:0:0]```

Node the U is being set 3rd from the end still for the non numeric data at the end.

The error message seems to imply there is an additional attribute being added that the RRD doesn't have.

Interestingly, I don't appear to have snmpEnableAuthenTraps as a DS in my netstats-snmp.rrd

```
rrdtool dump netstats-snmp.rrd | grep name
                <name> snmpInPkts </name>
                <name> snmpOutPkts </name>
                <name> snmpInBadVersions </name>
                <name> snmpInBadCommunityN </name>
                <name> snmpInBadCommunityU </name>
                <name> snmpInASNParseErrs </name>
                <name> snmpInTooBigs </name>
                <name> snmpInNoSuchNames </name>
                <name> snmpInBadValues </name>
                <name> snmpInReadOnlys </name>
                <name> snmpInGenErrs </name>
                <name> snmpInTotalReqVars </name>
                <name> snmpInTotalSetVars </name>
                <name> snmpInGetRequests </name>
                <name> snmpInGetNexts </name>
                <name> snmpInSetRequests </name>
                <name> snmpInGetResponses </name>
                <name> snmpInTraps </name>
                <name> snmpOutTooBigs </name>
                <name> snmpOutNoSuchNames </name>
                <name> snmpOutBadValues </name>
                <name> snmpOutGenErrs </name>
                <name> snmpOutGetRequests </name>
                <name> snmpOutGetNexts </name>
                <name> snmpOutSetRequests </name>
                <name> snmpOutGetResponses </name>
                <name> snmpOutTraps </name>
                <name> snmpSilentDrops </name>
                <name> snmpProxyDrops </name>
 ```

I don't understand why null values are not being written to the RRD (as U), but it looks like to fix this we need to remove snmpEnableAuthenTraps from the data that is being written.

**Comment by geordish** [comment] 2016-05-22 20:23
Actually, looking at this, it appears that the reason this broke, is because the loop to find non numerics in the rrdtool_update function is subtlety different:
```php
            if (!is_numeric($v)) {
                $v = U;
            }
            $values[] = $v;
```

Because $v would be null for snmpEnableAuthenTraps, it wouldn't create a new index in $values.

Luckily, the RRD is created explicitly without this anyway. Should be trivial to fix. Will submit a PR.

**Comment by paulgear** [comment] 2016-05-22 20:47
Thanks for working that out, @geordish !

**Comment by mahabs** [comment] 2016-10-09 18:55
Hi,
I'm not sure whether I should post here or open another ticket but I'm having a similar problem.
I keep getting the following errors:

Oct  9 13:25:47 librenms001 rrdcached[24709]: queue_thread_main: rrd_update_r (/data/librenms/rrd/././hostname1/netstats-snmp.rrd) failed with status -1. (/data/librenms/rrd/././hostname1/netstats-snmp.rrd: found extra data on update argument: 0)

Oct  9 14:12:12 librenms001 rrdcached[24709]: queue_thread_main: rrd_update_r (/data/librenms/rrd/././hostname2/netstats-snmp.rrd) failed with status -1. (/data/librenms/rrd/././hostname2/netstats-snmp.rrd: expected 29 data source readings (got 28) from 1476036732)

I just did a git pull today (oct/9/2016) which means that I have the latest librenms code.
I'm running rrdcached 1.4

**Comment by laf** [comment] 2016-10-09 19:24
Please post the output of ./validate.php

**Comment by mahabs** [comment] 2016-10-09 19:39
./validate.php
==========================================================
LibreNMS Version: ab8dd6eb438fd840f4168acd57f3b274ba78beb6
DB Schema: 114
PHP: 5.5.9-1ubuntu4.14
MySQL: 5.7.14-8-log
RRDTool: 1.4.7
SNMP: NET-SNMP 5.7.2
==========================================================

[WARN]  Your install is out of date, last update: Sun, 09 Oct 2016 11:00:07 +0000
[OK]    Database connection successful
[FAIL]  The poller has not run in the last 5 minutes, check the cron job
[FAIL]  Some devices have not completed their polling run in 5 minutes, this will create gaps in data.
        Check your poll log and refer to http://docs.librenms.org/Support/Performance/

**Comment by mahabs** [comment] 2016-10-10 16:36
@laf, any idea on how this can be fixed? is there a way to ignore the extra data and replace the missing data with null or something similar?

**Comment by murrant** [comment] 2016-10-13 17:16
@mahabs That is what the code does, I don't see how this can happen.

Can you post the output of `./poller.php -h HOSTNAME -m netstats-snmp -d` (between the load and unload netstats-snmp)

**Comment by mahabs** [comment] 2016-10-14 13:53
@murrant :
[pollingOutput.txt](https://github.com/librenms/librenms/files/529651/pollingOutput.txt)

**Comment by murrant** [comment] 2016-10-14 21:46
That output shows proper functionality.  There are 29 datapoints being writting to the netstats-snmp.rrd

```
RRD[update HOSTNAME01/netstats-snmp.rrd N:258450622:258451278:0:108:0:0:0:0:0:0:0:38993459:0:27353191:306335:0:0:0:0:0:0:0:0:0:0:258450515:765:0:0 --daemon LIBRE_IP:42217]
```

**Comment by laf** [comment] 2016-10-15 16:37
Maybe delete the file and let it be re-created?

**Comment by mbs91** [comment] 2016-10-20 10:38
We're using distributed polling and some of the pollers had old librenms code version. we made sure that all of the pollers are up to date and that error disappeared.

However, we're getting a new error now:
Oct 20 06:27:23 LIBRENMSMASTER rrdcached[17884]: queue_thread_main: rrd_update_r (/data/librenms/rrd/HOSTNAME001/netstats-tcp.rrd) failed with status -1. (/data/librenms/rrd/HOSTNAME001/netstats-tcp.rrd: expected 10 data source readings (got 9) from 1476955926)

any idea?

**Closed** 2016-11-19 15:03 UTC
Labels: Bug, Polling
