### ISSUE TITLE
Option to add comment/note when acknowledging an alert

### ISSUE THREAD

**Issue by mjclancy83** [librenms/librenms#3653] opened 2016-06-14 02:10 UTC
Hi Guys,

I was thinking it would be useful to have the option to add a comment when muting/acknowledging an alert?  In a team environment it is often useful to be able to see at a glance why one of your colleagues has muted an alert or acknowledged it.  If the comment could remain associated with the alert that would be useful, and displayed in relevant areas of the GUI.

Thanks and regards,

Matthew

**Comment by laf** [comment] 2016-06-14 07:04
Duplicate of #2472

Please register your interest on that issue.

**Closed by laf** 2016-06-14 07:04 UTC

**Comment by laf** [comment] 2018-03-21 15:48
Pull request now in https://github.com/librenms/librenms/pull/8433
