### ISSUE TITLE
Dynamic dash widget for alerts doesn't expand port alarms

### ISSUE THREAD

**Issue by rasssta** [librenms/librenms#1616] opened 2015-08-05 12:43 UTC
If I have a port alarm on a device and look at it under /alerts/ I can click the "+" to expand a list of ports on the device that are currently alarming.

I would like the same feature in the Alerts widget in the Dynamic Dash

**Comment by laf** [comment] 2015-08-06 20:43
Went to do this and it works for me. That's from the widget in the dashboard.

If it still doesn't work for you on latest version can you provide browser details please.

![image](https://cloud.githubusercontent.com/assets/3941142/9122930/26d42614-3c84-11e5-8e33-f5f9ce34daa8.png)

**Comment by rasssta** [comment] 2015-08-06 21:51
Hm, still doesn't work. Chrome on OS X 10.10.4.

Works in Safari on the same client though!

**Comment by laf** [comment] 2015-08-07 07:00
That's really odd as I'm on osx as well. I'll check my version numbers later

**Comment by f0o** [comment] 2015-08-07 10:15
Works here using Linux, Chromium 39.0.2171.65

**Comment by Rosiak** [comment] 2015-08-07 18:28
Only see the issue with the widget. /alert/ page works fine.
I'm able to reproduce in chrome and firefox on 2 different machines.

- Add Widget, see if it works(It does)
- Refresh page, see if it works(It doesn't)

**Comment by f0o** [comment] 2015-08-08 07:32
Re-Verified it on a couple of more OS & Browsers:

| OS | Arch | Browser | Version | Works? |
|------|--------|-------------|------------|-----------|
| Linux | i386 | Chromium | 39.0.2171.65 (Developer Build) | Yes |
| Linux | i386 | Google Chrome | 43.0.2357.65 (Official Build) | Yes |
| Android | ARMv7-A | Google Chrome | 44.0.2403.133 (Official Build) | Yes |
| Android | ARMv7-A | Firefox | 39.0 (Stable, Upstream) | Yes |
| OS X | x86_64 | Google Chrome | 44.0.2403.107 (Official Build) | Yes |
| OS X | x86_64 | Opera | 12.16 Build 1860 (Official, Presto) | Yes |
| OS X | x86_64 | Safari | 8.0.6 Build 10600.6.3 (Official, Upstream) | Yes |

**Comment by rasssta** [comment] 2015-08-08 07:38
I'm having the problems with OS X / x86_64 / Google Chrome / Version 44.0.2403.125 (64-bit).

On the same machine it works fine with OS X / x86_64 / Safari / 8.0.7

**Comment by rasssta** [comment] 2015-08-08 07:38
It works for me on the demo page in Chrome.

**Comment by f0o** [comment] 2015-08-08 07:46
Is your install up2date?

**Comment by rasssta** [comment] 2015-08-08 08:12
Yes

**Comment by laf** [comment] 2015-08-08 08:15
What other widgets are added?

**Comment by laf** [comment] 2015-08-08 09:45
Fixed in #1646

**Closed by laf** 2015-08-08 09:45 UTC
Labels: Needs-Info, WebUI
