### ISSUE TITLE
poller-wrapper.py not running (Missing config) since 2021-09-28 00:15:00 update

### ISSUE THREAD

**Issue by TD-er** [librenms/librenms#13287] opened 2021-09-28 14:30 UTC
### The problem

```
librenms@mon:~$ /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16
Cronic detected failure or error output for the command:
/opt/librenms/poller-wrapper.py 16

RESULT CODE: 1

ERROR OUTPUT:
ERROR: Could not execute command [['/usr/bin/env', 'php', '/opt/librenms/config_to_json.php']]: Expecting value: line 1 column 1 (char 0)
Could not run poller wrapper. Missing config
```

Initially mentioned it [here](https://github.com/librenms/librenms/issues/13282#issuecomment-929275317), but it is apparently a different issue.

### Output of ./validate.php

```txt
====================================
Component | Version
--------- | -------
LibreNMS  | 21.9.0-28-g5a0ed5751
DB Schema | 2021_08_26_093522_config_value_to_medium_text (217)
PHP       | 7.4.3
Python    | 3.8.10
MySQL     | 10.3.31-MariaDB-0ubuntu0.20.04.1
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[ESC[32mOKESC[0m]    Composer Version: 2.1.8
[ESC[32mOKESC[0m]    Dependencies up-to-date.
[ESC[0;32mOKESC[0m]    Database connection successful
[ESC[1;31mFAILESC[0m]  Database: incorrect column (notifications/datetime)
[ESC[1;31mFAILESC[0m]  Database: incorrect column (users/created_at)
[ESC[1;31mFAILESC[0m]  We have detected that your database schema may be wrong, please report the following to us on Discord (https://t.libren.ms/discord) or the community site (https://t.libren.ms/5gscd):
        [ESC[1;34mFIXESC[0m]:
        ESC[1;34mRun the following SQL statements to fix.ESC[0m
        SQL Statements:
         SET TIME_ZONE='+00:00';
         ALTER TABLE `notifications` CHANGE `datetime` `datetime` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ;
         ALTER TABLE `users` CHANGE `created_at` `created_at` timestamp NOT NULL DEFAULT '1970-01-02 00:00:01' ;
```
```


### What was the last working version of LibreNMS?

Yesterday's daily version

### Anything in the logs that might be useful for us?

_No response_

**Comment by TD-er** [comment] 2021-09-28 15:31
Just a small update. Getting the output from validate.php, I just wrote std output to a tmp file.
However I do see a lot of these on the (error) output:
```
Cannot adopt OID in UCD-DISKIO-MIB: diskIOTable ::= { ucdDiskIOMIB 1 }
Cannot adopt OID in NET-SNMP-AGENT-MIB: nsLoggingGroup ::= { nsConfigGroups 2 }
Cannot adopt OID in NET-SNMP-AGENT-MIB: nsDebugGroup ::= { nsConfigGroups 1 }
Cannot adopt OID in UCD-SNMP-MIB: snmperrErrMessage ::= { snmperrs 101 }
```
Maybe that can affect the config parsing?
The `config_to_json.php` does generate valid JSON, but it also outputs the same errors as above.

**Comment by TD-er** [comment] 2021-09-28 20:37
Found the fix, for Ubuntu 20.04:

```
apt-get install snmp-mibs-downloader
```
This does get rid of the hundreds of messages like these:
```
Cannot adopt OID in NET-SNMP-EXTEND-MIB: nsExtendResult ::= { nsExtendOutput1Entry 4 }
Cannot adopt OID in NET-SNMP-EXTEND-MIB: nsExtendOutNumLines ::= { nsExtendOutput1Entry 3 }
Cannot adopt OID in NET-SNMP-EXTEND-MIB: nsExtendOutputFull ::= { nsExtendOutput1Entry 2 }
Cannot adopt OID in NET-SNMP-EXTEND-MIB: nsExtendOutput1Line ::= { nsExtendOutput1Entry 1 }
Cannot adopt OID in NET-SNMP-EXTEND-MIB: nsExtendOutLine ::= { nsExtendOutput2Entry 2 }
Cannot adopt OID in NET-SNMP-EXTEND-MIB: nsExtendLineIndex ::= { nsExtendOutput2Entry 1 }
Cannot adopt OID in NET-SNMP-AGENT-MIB: nsNotifyStart ::= { netSnmpNotifications 1 }
Cannot adopt OID in NET-SNMP-AGENT-MIB: nsNotifyShutdown ::= { netSnmpNotifications 2 }
Cannot adopt OID in NET-SNMP-AGENT-MIB: nsNotifyRestart ::= { netSnmpNotifications 3 }
Cannot adopt OID in UCD-SNMP-MIB: laErrMessage ::= { laEntry 101 }
Cannot adopt OID in UCD-SNMP-MIB: laErrorFlag ::= { laEntry 100 }
Cannot adopt OID in UCD-SNMP-MIB: laLoadFloat ::= { laEntry 6 }
Cannot adopt OID in UCD-SNMP-MIB: laLoadInt ::= { laEntry 5 }
Cannot adopt OID in UCD-SNMP-MIB: laConfig ::= { laEntry 4 }
Cannot adopt OID in UCD-SNMP-MIB: laLoad ::= { laEntry 3 }
Cannot adopt OID in UCD-SNMP-MIB: laNames ::= { laEntry 2 }
Cannot adopt OID in UCD-SNMP-MIB: laIndex ::= { laEntry 1 }
```
And then the parsing of the config works again and the poller-wrapper.py is now polling again.

**Comment by murrant** [comment] 2021-09-29 00:36
These are in your snmp.conf file... Fix that and it will work.

Odd that it started causing an issue all of a sudden

**Comment by TD-er** [comment] 2021-09-29 08:29
Yep really odd, as I have not touched any settings and also have not ran `apt-get upgrade` etc for over a month.
It was the latest code that was parsing the config which was confused by the std error output.
So that makes me think it might not have parsed the config before?

**Comment by murrant** [comment] 2021-09-29 20:37
I think the python code started including stderr, so it was there before, just not included in the parsed output.

**Comment by murrant** [comment] 2021-09-30 04:13
Duplicate of #13282

**Closed by murrant** 2021-09-30 04:13 UTC
