### ISSUE TITLE
User not found in AD group

### ISSUE THREAD

**Issue by CZAirwolf** [librenms/librenms#7254] opened 2017-08-29 14:00 UTC
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

GitHub issues is for known/validated bugs, please do not post issues asking for help or how to do X, Y or Z. 

You can use our irc channel ##librenms on freenode to ask questions or our [community site](https://community.librenms.org).

If you have a feature request please post this on our [community site](https://community.librenms.org/c/feature-requests).

Please confirm each of the sections below by putting an `x` in the box like `[x]`.

- [x] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [x] Please include all of the information between the `====================================` section of `./validate.php` which you can run from the cli.
Component | Version
--------- | -------
LibreNMS  | 1.31.01
DB Schema | 205
PHP       | 7.0.19-1
MySQL     | 10.1.23-MariaDB-9+deb9u1
RRDTool   | 1.6.0
SNMP      | NET-SNMP 5.7.3
- [x] Please provide ALL info asked for [here](http://docs.librenms.org/Support/FAQ/#faq20).
No faq20 available.
Librenms Debian Stretch
AD is based on Samba (Debian Jessie), Win 2008r2 level
- [x] Please provide as much detail as possible.
Librenms can't find user in specified group in active directory. Tests showed, that pre 1.31.x (with added nested groups support) "html/includes/authentication/active_directory.inc.php" works (restored from backup), but 1.31.x doesn't work. It can find any user in active directory (with $config['auth_ad_require_groupmembership'] = false;), but not in group specified in config.php (with $config['auth_ad_require_groupmembership'] = true;). Comparing output from auth_test.php showed difference in search filters.
- [x] Please do NOT post more than 10 lines of debug information here, use a pastebin service or GitHub Gists.
PHP Fatal error:  Uncaught LibreNMS\Exceptions\AuthenticationException: User is not in one of the required groups or user/group is outside the base dn in /librenms/html/includes/authentication/active_directory.inc.php:50
Stack trace:
#0 /librenms/scripts/auth_test.php(96): authenticate('someuser', 'somepass')
#1 {main}
  thrown in /librenms/html/includes/authentication/active_directory.inc.php on line 50

Love librenms? Please consider supporting our collective:
👉  https://t.libren.ms/donations

**Comment by murrant** [comment] 2017-08-29 14:12
Can you give us more information about your AD layout and pastebin the results of `./scripts/auth_test.php -v`

I am not able to reproduce this with my Active Directory authentication.

**Comment by CZAirwolf** [comment] 2017-08-29 16:26
pre 1.31: https://pastebin.com/C0S4zznQ
1.31: https://pastebin.com/ywcXUaHr
config: https://pastebin.com/ADpeARWA

**Comment by fseesink** [comment] 2017-08-29 17:05
I'm going to need to toss my hat in the ring on this one.  Something has broken with regard to AD authentication that was working before.

This was manifested by users with restricted access (i.e., Normal users) saying they are no longer able to "see" any devices.  Note if _I_ login (with full admin rights), I'm still able to see devices fine as best I can tell.

This just began today, and I run a conservative setup, having followed the instructions here:
https://docs.librenms.org/General/Updating/

and configured LibreNMS from day one to only update to each stable release, as the page says "Choose this branch if you want to have a stable release."

But I see that LibreNMS WAS updated just yesterday (28 Aug 2017), so I'm going to go out on a limb that the update broke things.

Here's my setup:
```
Component | Version
--------- | -------
LibreNMS  | 1.31.01
DB Schema | 205
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3

```

And to be clear, here's the relevant portion of my config with regard to AD authentication and updates:
```
$config['auth_ad_require_groupmembership'] = true; // require users to be members of a group listed below
$config['auth_ad_groups']['traffic.wvnet.edu-ADMINS']['level'] = 10;
$config['auth_ad_groups']['Telcomm']['level'] = 10;
$config['auth_ad_groups']['Systems']['level'] = 5;
$config['auth_ad_groups']['traffic.wvnet.edu-GLOBAL-READ']['level'] = 5;
$config['auth_ad_groups']['traffic.wvnet.edu']['level']  = 1;
...
# Uncomment the next line to disable daily updates
#$config['update'] = 0;
$config['update_channel'] = 'release';
```

where I distinguish between

- those with administrative access to everything (AD groups '**traffic.wvnet.edu-ADMINS**' and '**Telcomm**'),
- those with global read access (AD groups '**Systems**' and '**traffic.wvnet.edu-GLOBAL-READ**'), and
- those who are normal users (AD group '**traffic.wvnet.edu**').

based on the information here:
https://docs.librenms.org/Extensions/Authentication/#user-levels

So far the only group affected are those setup as Normal users.

**Comment by laf** [comment] 2017-08-29 18:06
If you want to try replacing this file: https://raw.githubusercontent.com/librenms/librenms/50b3ffb3cfa8c9379ba4fbdef1341a43d4bea026/html/includes/authentication/active_directory.inc.php

and see if that fixes it so we can narrow down the commit then that would be ace.

**Comment by murrant** [comment] 2017-08-29 18:14
Hmm, perhaps the characters aren't properly escaped or something?

Can you try #7245 and see if it gives a more specific error?

**Comment by murrant** [comment] 2017-08-29 18:52
@fseesink Ok, I discovered the periods are causing your issue.

@CZAirwolf Does your group name have any periods in it?

**Comment by NetworkNub** [comment] 2017-08-29 18:59
#7257 fixed this issue for me.

**Comment by fseesink** [comment] 2017-08-29 20:25
@murrant and @laf,

Thanks!  Ok, now next question.  Considering I'd like to stick to stable releases otherwise, what is the best way to apply such a change?  Do I simply run

`./daily.sh`

as indicated in the docs?  Do I need to do the

```
cd /opt/librenms
git pull
php includes/sql-schema/update.php
```

commands?

**Comment by murrant** [comment] 2017-08-30 01:00
@fseesink Nothing, We reverted that patch for the stable release 1.31.1.  I would like to get it back into master if we can figure out the issue (I have a suspect).

I would suggest staying on stable releases.

**Comment by CZAirwolf** [comment] 2017-08-30 07:47
@laf I replaced the file with your posted version and voila, it works.
@murrant my groups have "_" in name, rest is alfanumeric.

**Comment by murrant** [comment] 2017-08-30 13:24
@CZAirwolf @fseesink @NetworkNub 

Can you test #7175 and see if that fixes your issues?  Thanks.

**Comment by fseesink** [comment] 2017-08-30 15:24
@murrant @CZAirwolf 

I'm afraid that revert didn't work.  After my initial post I had one user let me reset their AD password so I could go in as them to see what they were experiencing.  Sadly, today just as yesterday, this user, who SHOULD have global read access (they're part of the **traffic.wvnet.edu-GLOBAL-READ** AD group), could see NO devices at all.  It was if they were being treated as a Normal user.

Typically they are able to see all devices, just in read-only mode.  And until yesterday, this all worked well.  This particular user remembers using it last week without issue, and we don't really make changes to this server shy of standard Ubuntu updates.

@CZAirwolf regarding your last request, walk me through how you'd normally have me do that.  I'm used to doing basic git pulls of entire repos, but to test that #7259, what exactly would I need to do on my end?  And just as important, how do I roll it back if it doesn't work?

P.S.  To confirm the authentication file was reverted, I re-ran daily.sh as the librenms user and retested.  But still no go.

**Comment by NetworkNub** [comment] 2017-08-30 16:59
@murrant #7259 breaks AD login again. This toast message is displayed:
 
> Login error
> Invalid credentials

 Our group names contain alpha, spaces, and hyphens.

Output from ./scripts/auth_test.php -v :
> PHP Fatal error:  Uncaught LibreNMS\Exceptions\AuthenticationException: User is not in one of the required groups or user/group is outside the base dn in /opt/librenms/html/includes/authentication/active_directory.inc.php:49
> Stack trace:
> #0 /opt/librenms/scripts/auth_test.php(96): authenticate('***USERNAME***', '***PASSWORD***')
> #1 {main}
>   thrown in /opt/librenms/html/includes/authentication/active_directory.inc.php on line 49

**Comment by murrant** [comment] 2017-08-30 20:23
@fseesink That doesn't make much sense. This is the only change to AD auth.

@NetworkNub Can you give me more info?  Like I said I still can't reproduce this. So I need your help to figure out why it is breaking on your system.

**Comment by fseesink** [comment] 2017-08-30 21:23
@murrant 

Ok, ran ./validate.php and here's what you likely wanted to see:
```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.31.02
DB Schema | 205
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================
```

Now here's what I can tell you.  Since the issue appears to be that the AD auth code isn't supporting the full set of permitted characters for AD group names since you specifically mentioned the periods being an issue (and those ARE valid characters in AD naming), I decided to do my own testing.

I renamed the AD group from **traffic.wvnet.edu-GLOBAL-READ** to simply **LibreNMS-GLOBAL-READ** (notice just hyphens, no periods), adjusted the config.php file to match, and voila!  All devices reappeared for that same user account.

I then put everything back with the original names, and once again, it was if the user was defined as a Normal user (i.e., level 1) vs. a user with global-read privileges (i.e., level 5).

It does seem the AD auth code NOW is having issues with periods in AD group names, as until now (and we've had this instance in production since June) it was working just fine.

**Comment by murrant** [comment] 2017-08-31 04:08
@fseesink You only posted part of validate output, there should be at least two more lines.  I am concerned that you do not actually have the code reverted in your local install if you are still having issues on 1.30.2.

I do apologize for the issue as I tested this before hand but don't have any periods in my groups so I failed to see the subtle mistake that caused that error.  As always, any help testing patches is always appreciated.  By the way, the issue with periods in names should be fixed in the updated version of the nested groups support patch here: #7259.

**Comment by CZAirwolf** [comment] 2017-08-31 07:33
./scripts/github-apply 7259
error: unrecognized input

Anyway, i upgraded to: LibreNMS  | 1.31.02, auth doesn't works. But if i downloaded/replaced active_directory.inc.php with current version on github (patched 7259), it works.

**Comment by murrant** [comment] 2017-08-31 13:09
Thanks @CZAirwolf looks like 1.31.02 didn't include all the commits.  Thanks for informing us.

**Comment by fseesink** [comment] 2017-08-31 23:19
I re-ran
```
./daily.sh
```
and now everything's working as before.  Oh, and just for completeness, here's the output from validate.php:
```
...
====================================
Component | Version
--------- | -------
LibreNMS  | 1.31.03
DB Schema | 205
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.0.31-MariaDB-0ubuntu0.16.04.2
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  Your local git branch is not master, this will prevent automatic updates.
[WARN]  Your local git contains modified files, this could prevent automatic updates.
Modified files:
	 mibs/infoblox/IB-DHCPONE-MIB
	 mibs/infoblox/IB-DNSONE-MIB
	 mibs/infoblox/IB-PLATFORMONE-MIB
	 mibs/infoblox/IB-SMI-MIB
```

Note the updated MIB files are because we're polling some Infoblox appliances and I found the MIBs included weren't polling sufficiently for our needs, so I found updated versions.  (This, to be clear, has been in place since June, so nothing recent.)

But I'm guessing all you typically want to see are the lines between dashes and the 2 after regarding the database, correct?

**Comment by laf** [comment] 2017-09-01 14:13
To be fair we like to see all of it, helps in seeing if you've got other issues that might be related.

MIBs by themselves don't usually do anything, if these do or you've modified code then please submit those back to us upstream so others can benefit.

**Comment by NetworkNub** [comment] 2017-09-01 22:01
@murrant My AD is organized like this:

dc=example,dc=com
├── ou=corpUsers
│   ├── cn=User1
│   ├── cn=User2
│   ├── cn=User3
├── ou=corpGroups
│   ├── cn=Group1
│   ├── cn=Group2
│   └── cn=Group3

And my config looks like this:
```
$config['auth_ad_base_dn'] = "ou=corpUsers,dc=example,dc=com"
$config['auth_ad_groups']['Group1']['level'] = 5;
$config['auth_ad_groups']['Group2']['level'] = 10;
```

The original code did not care where the groups lived in AD. With #7259, AD groups must be under `auth_ad_base_dn` 

Changing the config to this fixed my login issue with #7259:

`$config['auth_ad_base_dn'] = "dc=example,dc=com"`

**Comment by murrant** [comment] 2017-09-04 22:21
@NetworkNub Interesting, that is the intended way base dn should work, it was just a quirk that it worked before.  Thanks for letting us know :)

**Comment by murrant** [comment] 2017-09-07 05:14
Closing this, please test #7259 and comment there.  Thanks.

**Closed by murrant** 2017-09-07 05:14 UTC
Labels: Bug
