### ISSUE TITLE
SNMP Trap Management

### ISSUE THREAD

**Issue by samyscoub** [librenms/librenms#3447] opened 2016-05-01 07:53 UTC
Hi,

First LibreNMS is a great tool !
The SNMP Trap handler feature seems not completely achieved.
Currently, it seems that just two types of SNMP traps are supported ( `linkUp` , `linkDown` ).

Can you confirm that even into libreNMS2, this support is not completely implemented ?

Currently i see that the "snmptrap.php" script is a wrapper for all scripts found into `'includes/snmptrap/'.$entry['1'].'.inc.php'; `
In my case, i've to manage about 250 snmp traps.

What is the best solution for me to add a patch into libreNMS to be the close to libreNMS philosophy ?

Thx

**Comment by laf** [comment] 2016-05-01 14:03
Duplicate of: #1380

At present we have no plans to add any further snmptrap support. If this is something you would like to contribute then that's perfectly fine. Please use the other issue to discuss this further.

**Closed by laf** 2016-05-01 14:03 UTC
